# File generated from our OpenAPI spec
defmodule Stripe.Params.V2.Core.Accounts.PersonCreateParams do
  @moduledoc "Parameters for person create."

  @typedoc """
  * `additional_addresses` - Additional addresses associated with the person.
  * `additional_names` - Additional names (e.g. aliases) associated with the person.
  * `additional_terms_of_service` - Attestations of accepted terms of service agreements.
  * `address` - The person's residential address.
  * `date_of_birth` - The person's date of birth.
  * `documents` - Documents that may be submitted to satisfy various informational requests.
  * `email` - Email.
  * `given_name` - The person's first name.
  * `id_numbers` - The identification numbers (e.g., SSN) associated with the person.
  * `legal_gender` - The person's gender (International regulations require either "male" or "female"). Possible values: `female`, `male`.
  * `metadata` - Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
  * `nationalities` - The nationalities (countries) this person is associated with.
  * `person_token` - The person token generated by the person token api.
  * `phone` - The phone number for this person.
  * `political_exposure` - The person's political exposure. Possible values: `existing`, `none`.
  * `relationship` - The relationship that this person has with the Account's business or legal entity.
  * `script_addresses` - The script addresses (e.g., non-Latin characters) associated with the person.
  * `script_names` - The script names (e.g. non-Latin characters) associated with the person.
  * `surname` - The person's last name.
  """
  @type t :: %__MODULE__{}

  defstruct [
    :additional_addresses,
    :additional_names,
    :additional_terms_of_service,
    :address,
    :date_of_birth,
    :documents,
    :email,
    :given_name,
    :id_numbers,
    :legal_gender,
    :metadata,
    :nationalities,
    :person_token,
    :phone,
    :political_exposure,
    :relationship,
    :script_addresses,
    :script_names,
    :surname
  ]
end
