# File generated from our OpenAPI spec
defmodule Stripe.Params.SubscriptionUpdateParams do
  @moduledoc "Parameters for subscription update."

  @typedoc """
  * `add_invoice_items` - A list of prices and quantities that will generate invoice items appended to the next invoice for this subscription. You may pass up to 20 items.
  * `application_fee_percent` - A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice total that will be transferred to the application owner's Stripe account. The request must be made by a platform account on a connected account in order to set an application fee percentage. For more information, see the application fees [documentation](https://stripe.com/docs/connect/subscriptions#collecting-fees-on-subscriptions).
  * `automatic_tax` - Automatic tax settings for this subscription. We recommend you only include this parameter when the existing value is being changed.
  * `billing_cycle_anchor` - Either `now` or `unchanged`. Setting the value to `now` resets the subscription's billing cycle anchor to the current time (in UTC). For more information, see the billing cycle [documentation](https://docs.stripe.com/billing/subscriptions/billing-cycle). Possible values: `now`, `unchanged`. Max length: 5000.
  * `billing_thresholds` - Define thresholds at which an invoice will be sent, and the subscription advanced to a new billing period. When updating, pass an empty string to remove previously-defined thresholds.
  * `cancel_at` - A timestamp at which the subscription should cancel. If set to a date before the current period ends, this will cause a proration if prorations have been enabled using `proration_behavior`. If set during a future period, this will always cause a proration for that period.
  * `cancel_at_period_end` - Indicate whether this subscription should cancel at the end of the current period (`current_period_end`). Defaults to `false`.
  * `cancellation_details` - Details about why this subscription was cancelled
  * `collection_method` - Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay this subscription at the end of the cycle using the default source attached to the customer. When sending an invoice, Stripe will email your customer an invoice with payment instructions and mark the subscription as `active`. Defaults to `charge_automatically`. Possible values: `charge_automatically`, `send_invoice`.
  * `days_until_due` - Number of days a customer has to pay invoices generated by this subscription. Valid only for subscriptions where `collection_method` is set to `send_invoice`.
  * `default_payment_method` - ID of the default payment method for the subscription. It must belong to the customer associated with the subscription. This takes precedence over `default_source`. If neither are set, invoices will use the customer's [invoice_settings.default_payment_method](https://docs.stripe.com/api/customers/object#customer_object-invoice_settings-default_payment_method) or [default_source](https://docs.stripe.com/api/customers/object#customer_object-default_source). Max length: 5000.
  * `default_source` - ID of the default payment source for the subscription. It must belong to the customer associated with the subscription and be in a chargeable state. If `default_payment_method` is also set, `default_payment_method` will take precedence. If neither are set, invoices will use the customer's [invoice_settings.default_payment_method](https://docs.stripe.com/api/customers/object#customer_object-invoice_settings-default_payment_method) or [default_source](https://docs.stripe.com/api/customers/object#customer_object-default_source).
  * `default_tax_rates` - The tax rates that will apply to any subscription item that does not have `tax_rates` set. Invoices created will have their `default_tax_rates` populated from the subscription. Pass an empty string to remove previously-defined tax rates.
  * `description` - The subscription's description, meant to be displayable to the customer. Use this field to optionally store an explanation of the subscription for rendering in Stripe surfaces and certain local payment methods UIs.
  * `discounts` - The coupons to redeem into discounts for the subscription. If not specified or empty, inherits the discount from the subscription's customer.
  * `expand` - Specifies which fields in the response should be expanded.
  * `invoice_settings` - All invoices will be billed using the specified settings.
  * `items` - A list of up to 20 subscription items, each with an attached price.
  * `metadata` - Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
  * `off_session` - Indicates if a customer is on or off-session while an invoice payment is attempted. Defaults to `false` (on-session).
  * `on_behalf_of` - The account on behalf of which to charge, for each of the subscription's invoices.
  * `pause_collection` - If specified, payment collection for this subscription will be paused. Note that the subscription status will be unchanged and will not be updated to `paused`. Learn more about [pausing collection](https://docs.stripe.com/billing/subscriptions/pause-payment).
  * `payment_behavior` - Use `allow_incomplete` to transition the subscription to `status=past_due` if a payment is required but cannot be paid. This allows you to manage scenarios where additional user actions are needed to pay a subscription's invoice. For example, SCA regulation may require 3DS authentication to complete payment. See the [SCA Migration Guide](https://docs.stripe.com/billing/migration/strong-customer-authentication) for Billing to learn more. This is the default behavior.

  Use `default_incomplete` to transition the subscription to `status=past_due` when payment is required and await explicit confirmation of the invoice's payment intent. This allows simpler management of scenarios where additional user actions are needed to pay a subscription’s invoice. Such as failed payments, [SCA regulation](https://docs.stripe.com/billing/migration/strong-customer-authentication), or collecting a mandate for a bank debit payment method.

  Use `pending_if_incomplete` to update the subscription using [pending updates](https://docs.stripe.com/billing/subscriptions/pending-updates). When you use `pending_if_incomplete` you can only pass the parameters [supported by pending updates](https://docs.stripe.com/billing/pending-updates-reference#supported-attributes).

  Use `error_if_incomplete` if you want Stripe to return an HTTP 402 status code if a subscription's invoice cannot be paid. For example, if a payment method requires 3DS authentication due to SCA regulation and further user action is needed, this parameter does not update the subscription and returns an error instead. This was the default behavior for API versions prior to 2019-03-14. See the [changelog](https://docs.stripe.com/changelog/2019-03-14) to learn more. Possible values: `allow_incomplete`, `default_incomplete`, `error_if_incomplete`, `pending_if_incomplete`.
  * `payment_settings` - Payment settings to pass to invoices created by the subscription.
  * `pending_invoice_item_interval` - Specifies an interval for how often to bill for any pending invoice items. It is analogous to calling [Create an invoice](https://docs.stripe.com/api#create_invoice) for the given subscription at the specified interval.
  * `proration_behavior` - Determines how to handle [prorations](https://docs.stripe.com/billing/subscriptions/prorations) when the billing cycle changes (e.g., when switching plans, resetting `billing_cycle_anchor=now`, or starting a trial), or if an item's `quantity` changes. The default value is `create_prorations`. Possible values: `always_invoice`, `create_prorations`, `none`.
  * `proration_date` - If set, prorations will be calculated as though the subscription was updated at the given time. This can be used to apply exactly the same prorations that were previewed with the [create preview](https://stripe.com/docs/api/invoices/create_preview) endpoint. `proration_date` can also be used to implement custom proration logic, such as prorating by day instead of by second, by providing the time that you wish to use for proration calculations. Format: Unix timestamp.
  * `transfer_data` - If specified, the funds from the subscription's invoices will be transferred to the destination and the ID of the resulting transfers will be found on the resulting charges. This will be unset if you POST an empty value.
  * `trial_end` - Unix timestamp representing the end of the trial period the customer will get before being charged for the first time. This will always overwrite any trials that might apply via a subscribed plan. If set, `trial_end` will override the default trial period of the plan the customer is being subscribed to. The `billing_cycle_anchor` will be updated to the `trial_end` value. The special value `now` can be provided to end the customer's trial immediately. Can be at most two years from `billing_cycle_anchor`.
  * `trial_from_plan` - Indicates if a plan's `trial_period_days` should be applied to the subscription. Setting `trial_end` per subscription is preferred, and this defaults to `false`. Setting this flag to `true` together with `trial_end` is not allowed. See [Using trial periods on subscriptions](https://docs.stripe.com/billing/subscriptions/trials) to learn more.
  * `trial_settings` - Settings related to subscription trials.
  """
  @type t :: %__MODULE__{
          add_invoice_items: [__MODULE__.AddInvoiceItems.t()] | nil,
          application_fee_percent: map() | nil,
          automatic_tax: __MODULE__.AutomaticTax.t() | nil,
          billing_cycle_anchor: String.t() | nil,
          billing_thresholds: map() | nil,
          cancel_at: map() | nil,
          cancel_at_period_end: boolean() | nil,
          cancellation_details: __MODULE__.CancellationDetails.t() | nil,
          collection_method: String.t() | nil,
          days_until_due: integer() | nil,
          default_payment_method: String.t() | nil,
          default_source: map() | nil,
          default_tax_rates: map() | nil,
          description: map() | nil,
          discounts: map() | nil,
          expand: [String.t()] | nil,
          invoice_settings: __MODULE__.InvoiceSettings.t() | nil,
          items: [__MODULE__.Items.t()] | nil,
          metadata: map() | nil,
          off_session: boolean() | nil,
          on_behalf_of: map() | nil,
          pause_collection: map() | nil,
          payment_behavior: String.t() | nil,
          payment_settings: __MODULE__.PaymentSettings.t() | nil,
          pending_invoice_item_interval: map() | nil,
          proration_behavior: String.t() | nil,
          proration_date: integer() | nil,
          transfer_data: map() | nil,
          trial_end: map() | nil,
          trial_from_plan: boolean() | nil,
          trial_settings: __MODULE__.TrialSettings.t() | nil
        }

  defstruct [
    :add_invoice_items,
    :application_fee_percent,
    :automatic_tax,
    :billing_cycle_anchor,
    :billing_thresholds,
    :cancel_at,
    :cancel_at_period_end,
    :cancellation_details,
    :collection_method,
    :days_until_due,
    :default_payment_method,
    :default_source,
    :default_tax_rates,
    :description,
    :discounts,
    :expand,
    :invoice_settings,
    :items,
    :metadata,
    :off_session,
    :on_behalf_of,
    :pause_collection,
    :payment_behavior,
    :payment_settings,
    :pending_invoice_item_interval,
    :proration_behavior,
    :proration_date,
    :transfer_data,
    :trial_end,
    :trial_from_plan,
    :trial_settings
  ]

  defmodule AddInvoiceItems do
    @moduledoc "Nested parameters."

    @typedoc """
    * `discounts` - The coupons to redeem into discounts for the item.
    * `metadata` - Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
    * `period` - The period associated with this invoice item. If not set, `period.start.type` defaults to `max_item_period_start` and `period.end.type` defaults to `min_item_period_end`.
    * `price` - The ID of the price object. One of `price` or `price_data` is required. Max length: 5000.
    * `price_data` - Data used to generate a new [Price](https://docs.stripe.com/api/prices) object inline. One of `price` or `price_data` is required.
    * `quantity` - Quantity for this item. Defaults to 1.
    * `tax_rates` - The tax rates which apply to the item. When set, the `default_tax_rates` do not apply to this item.
    """
    @type t :: %__MODULE__{
            discounts: [__MODULE__.Discounts.t()] | nil,
            metadata: %{String.t() => String.t()} | nil,
            period: __MODULE__.Period.t() | nil,
            price: String.t() | nil,
            price_data: __MODULE__.PriceData.t() | nil,
            quantity: integer() | nil,
            tax_rates: map() | nil
          }
    defstruct [:discounts, :metadata, :period, :price, :price_data, :quantity, :tax_rates]

    defmodule Discounts do
      @moduledoc "Nested parameters."

      @typedoc """
      * `coupon` - ID of the coupon to create a new discount for. Max length: 5000.
      * `discount` - ID of an existing discount on the object (or one of its ancestors) to reuse. Max length: 5000.
      * `promotion_code` - ID of the promotion code to create a new discount for. Max length: 5000.
      """
      @type t :: %__MODULE__{
              coupon: String.t() | nil,
              discount: String.t() | nil,
              promotion_code: String.t() | nil
            }
      defstruct [:coupon, :discount, :promotion_code]
    end

    defmodule Period do
      @moduledoc "Nested parameters."

      @typedoc """
      * `end` - End of the invoice item period.
      * `start` - Start of the invoice item period.
      """
      @type t :: %__MODULE__{
              end: __MODULE__.End.t() | nil,
              start: __MODULE__.Start.t() | nil
            }
      defstruct [:end, :start]

      defmodule End do
        @moduledoc "Nested parameters."

        @typedoc """
        * `timestamp` - A precise Unix timestamp for the end of the invoice item period. Must be greater than or equal to `period.start`. Format: Unix timestamp.
        * `type` - Select how to calculate the end of the invoice item period. Possible values: `min_item_period_end`, `timestamp`.
        """
        @type t :: %__MODULE__{
                timestamp: integer() | nil,
                type: String.t() | nil
              }
        defstruct [:timestamp, :type]
      end

      defmodule Start do
        @moduledoc "Nested parameters."

        @typedoc """
        * `timestamp` - A precise Unix timestamp for the start of the invoice item period. Must be less than or equal to `period.end`. Format: Unix timestamp.
        * `type` - Select how to calculate the start of the invoice item period. Possible values: `max_item_period_start`, `now`, `timestamp`.
        """
        @type t :: %__MODULE__{
                timestamp: integer() | nil,
                type: String.t() | nil
              }
        defstruct [:timestamp, :type]
      end
    end

    defmodule PriceData do
      @moduledoc "Nested parameters."

      @typedoc """
      * `currency` - Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies). Format: ISO 4217 currency code.
      * `product` - The ID of the [Product](https://docs.stripe.com/api/products) that this [Price](https://docs.stripe.com/api/prices) will belong to. Max length: 5000.
      * `tax_behavior` - Only required if a [default tax behavior](https://docs.stripe.com/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed. Possible values: `exclusive`, `inclusive`, `unspecified`.
      * `unit_amount` - A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge or a negative integer representing the amount to credit to the customer.
      * `unit_amount_decimal` - Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unit_amount` and `unit_amount_decimal` can be set. Format: decimal string.
      """
      @type t :: %__MODULE__{
              currency: String.t() | nil,
              product: String.t() | nil,
              tax_behavior: String.t() | nil,
              unit_amount: integer() | nil,
              unit_amount_decimal: String.t() | nil
            }
      defstruct [:currency, :product, :tax_behavior, :unit_amount, :unit_amount_decimal]
    end
  end

  defmodule AutomaticTax do
    @moduledoc "Nested parameters."

    @typedoc """
    * `enabled` - Enabled automatic tax calculation which will automatically compute tax rates on all invoices generated by the subscription.
    * `liability` - The account that's liable for tax. If set, the business address and tax registrations required to perform the tax calculation are loaded from this account. The tax transaction is returned in the report of the connected account.
    """
    @type t :: %__MODULE__{
            enabled: boolean() | nil,
            liability: __MODULE__.Liability.t() | nil
          }
    defstruct [:enabled, :liability]

    defmodule Liability do
      @moduledoc "Nested parameters."

      @typedoc """
      * `account` - The connected account being referenced when `type` is `account`.
      * `type` - Type of the account referenced in the request. Possible values: `account`, `self`.
      """
      @type t :: %__MODULE__{
              account: String.t() | nil,
              type: String.t() | nil
            }
      defstruct [:account, :type]
    end
  end

  defmodule CancellationDetails do
    @moduledoc "Nested parameters."

    @typedoc """
    * `comment` - Additional comments about why the user canceled the subscription, if the subscription was canceled explicitly by the user.
    * `feedback` - The customer submitted reason for why they canceled, if the subscription was canceled explicitly by the user. Possible values: `customer_service`, `low_quality`, `missing_features`, `other`, `switched_service`, `too_complex`, `too_expensive`, `unused`.
    """
    @type t :: %__MODULE__{
            comment: map() | nil,
            feedback: String.t() | nil
          }
    defstruct [:comment, :feedback]
  end

  defmodule InvoiceSettings do
    @moduledoc "Nested parameters."

    @typedoc """
    * `account_tax_ids` - The account tax IDs associated with the subscription. Will be set on invoices generated by the subscription.
    * `issuer` - The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
    """
    @type t :: %__MODULE__{
            account_tax_ids: map() | nil,
            issuer: __MODULE__.Issuer.t() | nil
          }
    defstruct [:account_tax_ids, :issuer]

    defmodule Issuer do
      @moduledoc "Nested parameters."

      @typedoc """
      * `account` - The connected account being referenced when `type` is `account`.
      * `type` - Type of the account referenced in the request. Possible values: `account`, `self`.
      """
      @type t :: %__MODULE__{
              account: String.t() | nil,
              type: String.t() | nil
            }
      defstruct [:account, :type]
    end
  end

  defmodule Items do
    @moduledoc "Nested parameters."

    @typedoc """
    * `billing_thresholds` - Define thresholds at which an invoice will be sent, and the subscription advanced to a new billing period. Pass an empty string to remove previously-defined thresholds.
    * `clear_usage` - Delete all usage for a given subscription item. You must pass this when deleting a usage records subscription item. `clear_usage` has no effect if the plan has a billing meter attached.
    * `deleted` - A flag that, if set to `true`, will delete the specified item.
    * `discounts` - The coupons to redeem into discounts for the subscription item.
    * `id` - Subscription item to update. Max length: 5000.
    * `metadata` - Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
    * `plan` - Plan ID for this item, as a string. Max length: 5000.
    * `price` - The ID of the price object. One of `price` or `price_data` is required. When changing a subscription item's price, `quantity` is set to 1 unless a `quantity` parameter is provided. Max length: 5000.
    * `price_data` - Data used to generate a new [Price](https://docs.stripe.com/api/prices) object inline. One of `price` or `price_data` is required.
    * `quantity` - Quantity for this item.
    * `tax_rates` - A list of [Tax Rate](https://docs.stripe.com/api/tax_rates) ids. These Tax Rates will override the [`default_tax_rates`](https://docs.stripe.com/api/subscriptions/create#create_subscription-default_tax_rates) on the Subscription. When updating, pass an empty string to remove previously-defined tax rates.
    """
    @type t :: %__MODULE__{
            billing_thresholds: map() | nil,
            clear_usage: boolean() | nil,
            deleted: boolean() | nil,
            discounts: map() | nil,
            id: String.t() | nil,
            metadata: map() | nil,
            plan: String.t() | nil,
            price: String.t() | nil,
            price_data: __MODULE__.PriceData.t() | nil,
            quantity: integer() | nil,
            tax_rates: map() | nil
          }
    defstruct [
      :billing_thresholds,
      :clear_usage,
      :deleted,
      :discounts,
      :id,
      :metadata,
      :plan,
      :price,
      :price_data,
      :quantity,
      :tax_rates
    ]

    defmodule PriceData do
      @moduledoc "Nested parameters."

      @typedoc """
      * `currency` - Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies). Format: ISO 4217 currency code.
      * `product` - The ID of the [Product](https://docs.stripe.com/api/products) that this [Price](https://docs.stripe.com/api/prices) will belong to. Max length: 5000.
      * `recurring` - The recurring components of a price such as `interval` and `interval_count`.
      * `tax_behavior` - Only required if a [default tax behavior](https://docs.stripe.com/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed. Possible values: `exclusive`, `inclusive`, `unspecified`.
      * `unit_amount` - A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge.
      * `unit_amount_decimal` - Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unit_amount` and `unit_amount_decimal` can be set. Format: decimal string.
      """
      @type t :: %__MODULE__{
              currency: String.t() | nil,
              product: String.t() | nil,
              recurring: __MODULE__.Recurring.t() | nil,
              tax_behavior: String.t() | nil,
              unit_amount: integer() | nil,
              unit_amount_decimal: String.t() | nil
            }
      defstruct [
        :currency,
        :product,
        :recurring,
        :tax_behavior,
        :unit_amount,
        :unit_amount_decimal
      ]

      defmodule Recurring do
        @moduledoc "Nested parameters."

        @typedoc """
        * `interval` - Specifies billing frequency. Either `day`, `week`, `month` or `year`. Possible values: `day`, `month`, `week`, `year`.
        * `interval_count` - The number of intervals between subscription billings. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of three years interval allowed (3 years, 36 months, or 156 weeks).
        """
        @type t :: %__MODULE__{
                interval: String.t() | nil,
                interval_count: integer() | nil
              }
        defstruct [:interval, :interval_count]
      end
    end
  end

  defmodule PaymentSettings do
    @moduledoc "Nested parameters."

    @typedoc """
    * `payment_method_options` - Payment-method-specific configuration to provide to invoices created by the subscription.
    * `payment_method_types` - The list of payment method types (e.g. card) to provide to the invoice’s PaymentIntent. If not set, Stripe attempts to automatically determine the types to use by looking at the invoice’s default payment method, the subscription’s default payment method, the customer’s default payment method, and your [invoice template settings](https://dashboard.stripe.com/settings/billing/invoice). Should not be specified with payment_method_configuration
    * `save_default_payment_method` - Configure whether Stripe updates `subscription.default_payment_method` when payment succeeds. Defaults to `off` if unspecified. Possible values: `off`, `on_subscription`.
    """
    @type t :: %__MODULE__{
            payment_method_options: __MODULE__.PaymentMethodOptions.t() | nil,
            payment_method_types: map() | nil,
            save_default_payment_method: String.t() | nil
          }
    defstruct [:payment_method_options, :payment_method_types, :save_default_payment_method]

    defmodule PaymentMethodOptions do
      @moduledoc "Nested parameters."

      @typedoc """
      * `acss_debit` - This sub-hash contains details about the Canadian pre-authorized debit payment method options to pass to the invoice’s PaymentIntent.
      * `bancontact` - This sub-hash contains details about the Bancontact payment method options to pass to the invoice’s PaymentIntent.
      * `card` - This sub-hash contains details about the Card payment method options to pass to the invoice’s PaymentIntent.
      * `customer_balance` - This sub-hash contains details about the Bank transfer payment method options to pass to the invoice’s PaymentIntent.
      * `konbini` - This sub-hash contains details about the Konbini payment method options to pass to the invoice’s PaymentIntent.
      * `payto` - This sub-hash contains details about the PayTo payment method options to pass to the invoice’s PaymentIntent.
      * `sepa_debit` - This sub-hash contains details about the SEPA Direct Debit payment method options to pass to the invoice’s PaymentIntent.
      * `us_bank_account` - This sub-hash contains details about the ACH direct debit payment method options to pass to the invoice’s PaymentIntent.
      """
      @type t :: %__MODULE__{
              acss_debit: map() | nil,
              bancontact: map() | nil,
              card: map() | nil,
              customer_balance: map() | nil,
              konbini: map() | nil,
              payto: map() | nil,
              sepa_debit: map() | nil,
              us_bank_account: map() | nil
            }
      defstruct [
        :acss_debit,
        :bancontact,
        :card,
        :customer_balance,
        :konbini,
        :payto,
        :sepa_debit,
        :us_bank_account
      ]
    end
  end

  defmodule TrialSettings do
    @moduledoc "Nested parameters."

    @typedoc """
    * `end_behavior` - Defines how the subscription should behave when the user's free trial ends.
    """
    @type t :: %__MODULE__{
            end_behavior: __MODULE__.EndBehavior.t() | nil
          }
    defstruct [:end_behavior]

    defmodule EndBehavior do
      @moduledoc "Nested parameters."

      @typedoc """
      * `missing_payment_method` - Indicates how the subscription should change when the trial ends if the user did not provide a payment method. Possible values: `cancel`, `create_invoice`, `pause`.
      """
      @type t :: %__MODULE__{
              missing_payment_method: String.t() | nil
            }
      defstruct [:missing_payment_method]
    end
  end
end
