# File generated from our OpenAPI spec
defmodule Stripe.EventTypes do
  @moduledoc false

  @doc "Maps event type strings to the schema ref of the event's data object."
  def event_type_to_data_ref do
    %{
      "account.application.authorized" => "#/components/schemas/application",
      "account.application.deauthorized" => "#/components/schemas/application",
      "account.external_account.created" => nil,
      "account.external_account.deleted" => nil,
      "account.external_account.updated" => nil,
      "account.updated" => "#/components/schemas/account",
      "application_fee.created" => "#/components/schemas/application_fee",
      "application_fee.refund.updated" => "#/components/schemas/fee_refund",
      "application_fee.refunded" => "#/components/schemas/application_fee",
      "balance.available" => "#/components/schemas/balance",
      "balance_settings.updated" => "#/components/schemas/balance_settings",
      "billing.alert.triggered" => "#/components/schemas/billing.alert_triggered",
      "billing.credit_balance_transaction.created" =>
        "#/components/schemas/billing.credit_balance_transaction",
      "billing.credit_grant.created" => "#/components/schemas/billing.credit_grant",
      "billing.credit_grant.updated" => "#/components/schemas/billing.credit_grant",
      "billing.meter.created" => "#/components/schemas/billing.meter",
      "billing.meter.deactivated" => "#/components/schemas/billing.meter",
      "billing.meter.reactivated" => "#/components/schemas/billing.meter",
      "billing.meter.updated" => "#/components/schemas/billing.meter",
      "billing_portal.configuration.created" =>
        "#/components/schemas/billing_portal.configuration",
      "billing_portal.configuration.updated" =>
        "#/components/schemas/billing_portal.configuration",
      "billing_portal.session.created" => "#/components/schemas/billing_portal.session",
      "capability.updated" => "#/components/schemas/capability",
      "cash_balance.funds_available" => "#/components/schemas/cash_balance",
      "charge.captured" => "#/components/schemas/charge",
      "charge.dispute.closed" => "#/components/schemas/dispute",
      "charge.dispute.created" => "#/components/schemas/dispute",
      "charge.dispute.funds_reinstated" => "#/components/schemas/dispute",
      "charge.dispute.funds_withdrawn" => "#/components/schemas/dispute",
      "charge.dispute.updated" => "#/components/schemas/dispute",
      "charge.expired" => "#/components/schemas/charge",
      "charge.failed" => "#/components/schemas/charge",
      "charge.pending" => "#/components/schemas/charge",
      "charge.refund.updated" => "#/components/schemas/refund",
      "charge.refunded" => "#/components/schemas/charge",
      "charge.succeeded" => "#/components/schemas/charge",
      "charge.updated" => "#/components/schemas/charge",
      "checkout.session.async_payment_failed" => "#/components/schemas/checkout.session",
      "checkout.session.async_payment_succeeded" => "#/components/schemas/checkout.session",
      "checkout.session.completed" => "#/components/schemas/checkout.session",
      "checkout.session.expired" => "#/components/schemas/checkout.session",
      "climate.order.canceled" => "#/components/schemas/climate.order",
      "climate.order.created" => "#/components/schemas/climate.order",
      "climate.order.delayed" => "#/components/schemas/climate.order",
      "climate.order.delivered" => "#/components/schemas/climate.order",
      "climate.order.product_substituted" => "#/components/schemas/climate.order",
      "climate.product.created" => "#/components/schemas/climate.product",
      "climate.product.pricing_updated" => "#/components/schemas/climate.product",
      "coupon.created" => "#/components/schemas/coupon",
      "coupon.deleted" => "#/components/schemas/coupon",
      "coupon.updated" => "#/components/schemas/coupon",
      "credit_note.created" => "#/components/schemas/credit_note",
      "credit_note.updated" => "#/components/schemas/credit_note",
      "credit_note.voided" => "#/components/schemas/credit_note",
      "customer.created" => "#/components/schemas/customer",
      "customer.deleted" => "#/components/schemas/customer",
      "customer.discount.created" => "#/components/schemas/discount",
      "customer.discount.deleted" => "#/components/schemas/discount",
      "customer.discount.updated" => "#/components/schemas/discount",
      "customer.source.created" => nil,
      "customer.source.deleted" => nil,
      "customer.source.expiring" => nil,
      "customer.source.updated" => nil,
      "customer.subscription.created" => "#/components/schemas/subscription",
      "customer.subscription.deleted" => "#/components/schemas/subscription",
      "customer.subscription.paused" => "#/components/schemas/subscription",
      "customer.subscription.pending_update_applied" => "#/components/schemas/subscription",
      "customer.subscription.pending_update_expired" => "#/components/schemas/subscription",
      "customer.subscription.resumed" => "#/components/schemas/subscription",
      "customer.subscription.trial_will_end" => "#/components/schemas/subscription",
      "customer.subscription.updated" => "#/components/schemas/subscription",
      "customer.tax_id.created" => "#/components/schemas/tax_id",
      "customer.tax_id.deleted" => "#/components/schemas/tax_id",
      "customer.tax_id.updated" => "#/components/schemas/tax_id",
      "customer.updated" => "#/components/schemas/customer",
      "customer_cash_balance_transaction.created" =>
        "#/components/schemas/customer_cash_balance_transaction",
      "entitlements.active_entitlement_summary.updated" =>
        "#/components/schemas/entitlements.active_entitlement_summary",
      "file.created" => "#/components/schemas/file",
      "financial_connections.account.account_numbers_updated" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.created" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.deactivated" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.disconnected" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.reactivated" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.refreshed_balance" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.refreshed_ownership" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.refreshed_transactions" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.upcoming_account_number_expiry" =>
        "#/components/schemas/financial_connections.account",
      "identity.verification_session.canceled" =>
        "#/components/schemas/identity.verification_session",
      "identity.verification_session.created" =>
        "#/components/schemas/identity.verification_session",
      "identity.verification_session.processing" =>
        "#/components/schemas/identity.verification_session",
      "identity.verification_session.redacted" =>
        "#/components/schemas/identity.verification_session",
      "identity.verification_session.requires_input" =>
        "#/components/schemas/identity.verification_session",
      "identity.verification_session.verified" =>
        "#/components/schemas/identity.verification_session",
      "invoice.created" => "#/components/schemas/invoice",
      "invoice.deleted" => "#/components/schemas/invoice",
      "invoice.finalization_failed" => "#/components/schemas/invoice",
      "invoice.finalized" => "#/components/schemas/invoice",
      "invoice.marked_uncollectible" => "#/components/schemas/invoice",
      "invoice.overdue" => "#/components/schemas/invoice",
      "invoice.overpaid" => "#/components/schemas/invoice",
      "invoice.paid" => "#/components/schemas/invoice",
      "invoice.payment_action_required" => "#/components/schemas/invoice",
      "invoice.payment_attempt_required" => "#/components/schemas/invoice",
      "invoice.payment_failed" => "#/components/schemas/invoice",
      "invoice.payment_succeeded" => "#/components/schemas/invoice",
      "invoice.sent" => "#/components/schemas/invoice",
      "invoice.upcoming" => "#/components/schemas/invoice",
      "invoice.updated" => "#/components/schemas/invoice",
      "invoice.voided" => "#/components/schemas/invoice",
      "invoice.will_be_due" => "#/components/schemas/invoice",
      "invoice_payment.paid" => "#/components/schemas/invoice_payment",
      "invoiceitem.created" => "#/components/schemas/invoiceitem",
      "invoiceitem.deleted" => "#/components/schemas/invoiceitem",
      "issuing_authorization.created" => "#/components/schemas/issuing.authorization",
      "issuing_authorization.request" => "#/components/schemas/issuing.authorization",
      "issuing_authorization.updated" => "#/components/schemas/issuing.authorization",
      "issuing_card.created" => "#/components/schemas/issuing.card",
      "issuing_card.updated" => "#/components/schemas/issuing.card",
      "issuing_cardholder.created" => "#/components/schemas/issuing.cardholder",
      "issuing_cardholder.updated" => "#/components/schemas/issuing.cardholder",
      "issuing_dispute.closed" => "#/components/schemas/issuing.dispute",
      "issuing_dispute.created" => "#/components/schemas/issuing.dispute",
      "issuing_dispute.funds_reinstated" => "#/components/schemas/issuing.dispute",
      "issuing_dispute.funds_rescinded" => "#/components/schemas/issuing.dispute",
      "issuing_dispute.submitted" => "#/components/schemas/issuing.dispute",
      "issuing_dispute.updated" => "#/components/schemas/issuing.dispute",
      "issuing_personalization_design.activated" =>
        "#/components/schemas/issuing.personalization_design",
      "issuing_personalization_design.deactivated" =>
        "#/components/schemas/issuing.personalization_design",
      "issuing_personalization_design.rejected" =>
        "#/components/schemas/issuing.personalization_design",
      "issuing_personalization_design.updated" =>
        "#/components/schemas/issuing.personalization_design",
      "issuing_token.created" => "#/components/schemas/issuing.token",
      "issuing_token.updated" => "#/components/schemas/issuing.token",
      "issuing_transaction.created" => "#/components/schemas/issuing.transaction",
      "issuing_transaction.purchase_details_receipt_updated" =>
        "#/components/schemas/issuing.transaction",
      "issuing_transaction.updated" => "#/components/schemas/issuing.transaction",
      "mandate.updated" => "#/components/schemas/mandate",
      "payment_intent.amount_capturable_updated" => "#/components/schemas/payment_intent",
      "payment_intent.canceled" => "#/components/schemas/payment_intent",
      "payment_intent.created" => "#/components/schemas/payment_intent",
      "payment_intent.partially_funded" => "#/components/schemas/payment_intent",
      "payment_intent.payment_failed" => "#/components/schemas/payment_intent",
      "payment_intent.processing" => "#/components/schemas/payment_intent",
      "payment_intent.requires_action" => "#/components/schemas/payment_intent",
      "payment_intent.succeeded" => "#/components/schemas/payment_intent",
      "payment_link.created" => "#/components/schemas/payment_link",
      "payment_link.updated" => "#/components/schemas/payment_link",
      "payment_method.attached" => "#/components/schemas/payment_method",
      "payment_method.automatically_updated" => "#/components/schemas/payment_method",
      "payment_method.detached" => "#/components/schemas/payment_method",
      "payment_method.updated" => "#/components/schemas/payment_method",
      "payout.canceled" => "#/components/schemas/payout",
      "payout.created" => "#/components/schemas/payout",
      "payout.failed" => "#/components/schemas/payout",
      "payout.paid" => "#/components/schemas/payout",
      "payout.reconciliation_completed" => "#/components/schemas/payout",
      "payout.updated" => "#/components/schemas/payout",
      "person.created" => "#/components/schemas/person",
      "person.deleted" => "#/components/schemas/person",
      "person.updated" => "#/components/schemas/person",
      "plan.created" => "#/components/schemas/plan",
      "plan.deleted" => "#/components/schemas/plan",
      "plan.updated" => "#/components/schemas/plan",
      "price.created" => "#/components/schemas/price",
      "price.deleted" => "#/components/schemas/price",
      "price.updated" => "#/components/schemas/price",
      "product.created" => "#/components/schemas/product",
      "product.deleted" => "#/components/schemas/product",
      "product.updated" => "#/components/schemas/product",
      "promotion_code.created" => "#/components/schemas/promotion_code",
      "promotion_code.updated" => "#/components/schemas/promotion_code",
      "quote.accepted" => "#/components/schemas/quote",
      "quote.canceled" => "#/components/schemas/quote",
      "quote.created" => "#/components/schemas/quote",
      "quote.finalized" => "#/components/schemas/quote",
      "radar.early_fraud_warning.created" => "#/components/schemas/radar.early_fraud_warning",
      "radar.early_fraud_warning.updated" => "#/components/schemas/radar.early_fraud_warning",
      "refund.created" => "#/components/schemas/refund",
      "refund.failed" => "#/components/schemas/refund",
      "refund.updated" => "#/components/schemas/refund",
      "reporting.report_run.failed" => "#/components/schemas/reporting.report_run",
      "reporting.report_run.succeeded" => "#/components/schemas/reporting.report_run",
      "reporting.report_type.updated" => "#/components/schemas/reporting.report_type",
      "review.closed" => "#/components/schemas/review",
      "review.opened" => "#/components/schemas/review",
      "setup_intent.canceled" => "#/components/schemas/setup_intent",
      "setup_intent.created" => "#/components/schemas/setup_intent",
      "setup_intent.requires_action" => "#/components/schemas/setup_intent",
      "setup_intent.setup_failed" => "#/components/schemas/setup_intent",
      "setup_intent.succeeded" => "#/components/schemas/setup_intent",
      "sigma.scheduled_query_run.created" => "#/components/schemas/scheduled_query_run",
      "source.canceled" => "#/components/schemas/source",
      "source.chargeable" => "#/components/schemas/source",
      "source.failed" => "#/components/schemas/source",
      "source.mandate_notification" => "#/components/schemas/source_mandate_notification",
      "source.refund_attributes_required" => "#/components/schemas/source",
      "source.transaction.created" => "#/components/schemas/source_transaction",
      "source.transaction.updated" => "#/components/schemas/source_transaction",
      "subscription_schedule.aborted" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.canceled" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.completed" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.created" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.expiring" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.released" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.updated" => "#/components/schemas/subscription_schedule",
      "tax.settings.updated" => "#/components/schemas/tax.settings",
      "tax_rate.created" => "#/components/schemas/tax_rate",
      "tax_rate.updated" => "#/components/schemas/tax_rate",
      "terminal.reader.action_failed" => "#/components/schemas/terminal.reader",
      "terminal.reader.action_succeeded" => "#/components/schemas/terminal.reader",
      "terminal.reader.action_updated" => "#/components/schemas/terminal.reader",
      "test_helpers.test_clock.advancing" => "#/components/schemas/test_helpers.test_clock",
      "test_helpers.test_clock.created" => "#/components/schemas/test_helpers.test_clock",
      "test_helpers.test_clock.deleted" => "#/components/schemas/test_helpers.test_clock",
      "test_helpers.test_clock.internal_failure" =>
        "#/components/schemas/test_helpers.test_clock",
      "test_helpers.test_clock.ready" => "#/components/schemas/test_helpers.test_clock",
      "topup.canceled" => "#/components/schemas/topup",
      "topup.created" => "#/components/schemas/topup",
      "topup.failed" => "#/components/schemas/topup",
      "topup.reversed" => "#/components/schemas/topup",
      "topup.succeeded" => "#/components/schemas/topup",
      "transfer.created" => "#/components/schemas/transfer",
      "transfer.reversed" => "#/components/schemas/transfer",
      "transfer.updated" => "#/components/schemas/transfer",
      "treasury.credit_reversal.created" => "#/components/schemas/treasury.credit_reversal",
      "treasury.credit_reversal.posted" => "#/components/schemas/treasury.credit_reversal",
      "treasury.debit_reversal.completed" => "#/components/schemas/treasury.debit_reversal",
      "treasury.debit_reversal.created" => "#/components/schemas/treasury.debit_reversal",
      "treasury.debit_reversal.initial_credit_granted" =>
        "#/components/schemas/treasury.debit_reversal",
      "treasury.financial_account.closed" => "#/components/schemas/treasury.financial_account",
      "treasury.financial_account.created" => "#/components/schemas/treasury.financial_account",
      "treasury.financial_account.features_status_updated" =>
        "#/components/schemas/treasury.financial_account",
      "treasury.inbound_transfer.canceled" => "#/components/schemas/treasury.inbound_transfer",
      "treasury.inbound_transfer.created" => "#/components/schemas/treasury.inbound_transfer",
      "treasury.inbound_transfer.failed" => "#/components/schemas/treasury.inbound_transfer",
      "treasury.inbound_transfer.succeeded" => "#/components/schemas/treasury.inbound_transfer",
      "treasury.outbound_payment.canceled" => "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.created" => "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.expected_arrival_date_updated" =>
        "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.failed" => "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.posted" => "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.returned" => "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.tracking_details_updated" =>
        "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_transfer.canceled" => "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.created" => "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.expected_arrival_date_updated" =>
        "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.failed" => "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.posted" => "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.returned" => "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.tracking_details_updated" =>
        "#/components/schemas/treasury.outbound_transfer",
      "treasury.received_credit.created" => "#/components/schemas/treasury.received_credit",
      "treasury.received_credit.failed" => "#/components/schemas/treasury.received_credit",
      "treasury.received_credit.succeeded" => "#/components/schemas/treasury.received_credit",
      "treasury.received_debit.created" => "#/components/schemas/treasury.received_debit",
      "v1.billing.meter.error_report_triggered" => nil,
      "v1.billing.meter.no_meter_found" => nil,
      "v2.core.account.closed" => nil,
      "v2.core.account.created" => nil,
      "v2.core.account.updated" => nil,
      "v2.core.account[configuration.customer].capability_status_updated" => nil,
      "v2.core.account[configuration.customer].updated" => nil,
      "v2.core.account[configuration.merchant].capability_status_updated" => nil,
      "v2.core.account[configuration.merchant].updated" => nil,
      "v2.core.account[configuration.recipient].capability_status_updated" => nil,
      "v2.core.account[configuration.recipient].updated" => nil,
      "v2.core.account[defaults].updated" => nil,
      "v2.core.account[future_requirements].updated" => nil,
      "v2.core.account[identity].updated" => nil,
      "v2.core.account[requirements].updated" => nil,
      "v2.core.account_link.returned" => nil,
      "v2.core.account_person.created" => nil,
      "v2.core.account_person.deleted" => nil,
      "v2.core.account_person.updated" => nil,
      "v2.core.event_destination.ping" => nil
    }
  end

  @doc "Maps thin event type strings to their per-event typed module."
  def event_type_to_module do
    %{
      "v1.billing.meter.error_report_triggered" =>
        Stripe.Events.V1BillingMeterErrorReportTriggeredEvent,
      "v1.billing.meter.no_meter_found" => Stripe.Events.V1BillingMeterNoMeterFoundEvent,
      "v2.core.account.closed" => Stripe.Events.V2CoreAccountClosedEvent,
      "v2.core.account.created" => Stripe.Events.V2CoreAccountCreatedEvent,
      "v2.core.account.updated" => Stripe.Events.V2CoreAccountUpdatedEvent,
      "v2.core.account[configuration.customer].capability_status_updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationCustomerCapabilityStatusUpdatedEvent,
      "v2.core.account[configuration.customer].updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationCustomerUpdatedEvent,
      "v2.core.account[configuration.merchant].capability_status_updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationMerchantCapabilityStatusUpdatedEvent,
      "v2.core.account[configuration.merchant].updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationMerchantUpdatedEvent,
      "v2.core.account[configuration.recipient].capability_status_updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationRecipientCapabilityStatusUpdatedEvent,
      "v2.core.account[configuration.recipient].updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationRecipientUpdatedEvent,
      "v2.core.account[defaults].updated" =>
        Stripe.Events.V2CoreAccountIncludingDefaultsUpdatedEvent,
      "v2.core.account[future_requirements].updated" =>
        Stripe.Events.V2CoreAccountIncludingFutureRequirementsUpdatedEvent,
      "v2.core.account[identity].updated" =>
        Stripe.Events.V2CoreAccountIncludingIdentityUpdatedEvent,
      "v2.core.account[requirements].updated" =>
        Stripe.Events.V2CoreAccountIncludingRequirementsUpdatedEvent,
      "v2.core.account_link.returned" => Stripe.Events.V2CoreAccountLinkReturnedEvent,
      "v2.core.account_person.created" => Stripe.Events.V2CoreAccountPersonCreatedEvent,
      "v2.core.account_person.deleted" => Stripe.Events.V2CoreAccountPersonDeletedEvent,
      "v2.core.account_person.updated" => Stripe.Events.V2CoreAccountPersonUpdatedEvent,
      "v2.core.event_destination.ping" => Stripe.Events.V2CoreEventDestinationPingEvent
    }
  end
end
