# File generated from our OpenAPI spec
defmodule Stripe.EventTypes do
  @moduledoc false

  @doc "Maps event type strings to the schema ref of the event's data object."
  def event_type_to_data_ref do
    %{
      "account.application.authorized" => "#/components/schemas/application",
      "account.application.deauthorized" => "#/components/schemas/application",
      "account.external_account.created" => nil,
      "account.external_account.deleted" => nil,
      "account.external_account.updated" => nil,
      "account.updated" => "#/components/schemas/account",
      "application_fee.created" => "#/components/schemas/application_fee",
      "application_fee.refund.updated" => "#/components/schemas/fee_refund",
      "application_fee.refunded" => "#/components/schemas/application_fee",
      "apps.install.created" => "#/components/schemas/apps.install",
      "apps.install.deleted" => "#/components/schemas/apps.install",
      "apps.install.updated" => "#/components/schemas/apps.install",
      "balance.available" => "#/components/schemas/balance",
      "balance_settings.updated" => "#/components/schemas/balance_settings",
      "billing.alert.triggered" => "#/components/schemas/billing.alert_triggered",
      "billing.credit_balance_transaction.created" =>
        "#/components/schemas/billing.credit_balance_transaction",
      "billing.credit_grant.created" => "#/components/schemas/billing.credit_grant",
      "billing.credit_grant.updated" => "#/components/schemas/billing.credit_grant",
      "billing.meter.created" => "#/components/schemas/billing.meter",
      "billing.meter.deactivated" => "#/components/schemas/billing.meter",
      "billing.meter.reactivated" => "#/components/schemas/billing.meter",
      "billing.meter.updated" => "#/components/schemas/billing.meter",
      "billing_portal.configuration.created" =>
        "#/components/schemas/billing_portal.configuration",
      "billing_portal.configuration.updated" =>
        "#/components/schemas/billing_portal.configuration",
      "billing_portal.session.created" => "#/components/schemas/billing_portal.session",
      "capability.updated" => "#/components/schemas/capability",
      "cash_balance.funds_available" => "#/components/schemas/cash_balance",
      "charge.captured" => "#/components/schemas/charge",
      "charge.dispute.closed" => "#/components/schemas/dispute",
      "charge.dispute.created" => "#/components/schemas/dispute",
      "charge.dispute.funds_reinstated" => "#/components/schemas/dispute",
      "charge.dispute.funds_withdrawn" => "#/components/schemas/dispute",
      "charge.dispute.updated" => "#/components/schemas/dispute",
      "charge.expired" => "#/components/schemas/charge",
      "charge.failed" => "#/components/schemas/charge",
      "charge.pending" => "#/components/schemas/charge",
      "charge.refund.updated" => "#/components/schemas/refund",
      "charge.refunded" => "#/components/schemas/charge",
      "charge.succeeded" => "#/components/schemas/charge",
      "charge.updated" => "#/components/schemas/charge",
      "checkout.session.async_payment_failed" => "#/components/schemas/checkout.session",
      "checkout.session.async_payment_succeeded" => "#/components/schemas/checkout.session",
      "checkout.session.completed" => "#/components/schemas/checkout.session",
      "checkout.session.expired" => "#/components/schemas/checkout.session",
      "climate.order.canceled" => "#/components/schemas/climate.order",
      "climate.order.created" => "#/components/schemas/climate.order",
      "climate.order.delayed" => "#/components/schemas/climate.order",
      "climate.order.delivered" => "#/components/schemas/climate.order",
      "climate.order.product_substituted" => "#/components/schemas/climate.order",
      "climate.product.created" => "#/components/schemas/climate.product",
      "climate.product.pricing_updated" => "#/components/schemas/climate.product",
      "coupon.created" => "#/components/schemas/coupon",
      "coupon.deleted" => "#/components/schemas/coupon",
      "coupon.updated" => "#/components/schemas/coupon",
      "credit_note.created" => "#/components/schemas/credit_note",
      "credit_note.updated" => "#/components/schemas/credit_note",
      "credit_note.voided" => "#/components/schemas/credit_note",
      "customer.created" => "#/components/schemas/customer",
      "customer.deleted" => "#/components/schemas/customer",
      "customer.discount.created" => "#/components/schemas/discount",
      "customer.discount.deleted" => "#/components/schemas/discount",
      "customer.discount.updated" => "#/components/schemas/discount",
      "customer.source.created" => nil,
      "customer.source.deleted" => nil,
      "customer.source.expiring" => nil,
      "customer.source.updated" => nil,
      "customer.subscription.created" => "#/components/schemas/subscription",
      "customer.subscription.deleted" => "#/components/schemas/subscription",
      "customer.subscription.paused" => "#/components/schemas/subscription",
      "customer.subscription.pending_update_applied" => "#/components/schemas/subscription",
      "customer.subscription.pending_update_expired" => "#/components/schemas/subscription",
      "customer.subscription.resumed" => "#/components/schemas/subscription",
      "customer.subscription.trial_will_end" => "#/components/schemas/subscription",
      "customer.subscription.updated" => "#/components/schemas/subscription",
      "customer.tax_id.created" => "#/components/schemas/tax_id",
      "customer.tax_id.deleted" => "#/components/schemas/tax_id",
      "customer.tax_id.updated" => "#/components/schemas/tax_id",
      "customer.updated" => "#/components/schemas/customer",
      "customer_cash_balance_transaction.created" =>
        "#/components/schemas/customer_cash_balance_transaction",
      "entitlements.active_entitlement_summary.updated" =>
        "#/components/schemas/entitlements.active_entitlement_summary",
      "file.created" => "#/components/schemas/file",
      "financial_connections.account.account_numbers_updated" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.created" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.deactivated" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.disconnected" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.expected_deactivation_date_updated" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.reactivated" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.refreshed_balance" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.refreshed_ownership" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.refreshed_transactions" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.supported_payment_method_types_updated" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.upcoming_account_number_expiry" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.account.upcoming_deactivation" =>
        "#/components/schemas/financial_connections.account",
      "financial_connections.authorization.expected_deactivation_date_updated" =>
        "#/components/schemas/financial_connections.authorization",
      "financial_connections.authorization.upcoming_deactivation" =>
        "#/components/schemas/financial_connections.authorization",
      "identity.verification_session.canceled" =>
        "#/components/schemas/identity.verification_session",
      "identity.verification_session.created" =>
        "#/components/schemas/identity.verification_session",
      "identity.verification_session.processing" =>
        "#/components/schemas/identity.verification_session",
      "identity.verification_session.redacted" =>
        "#/components/schemas/identity.verification_session",
      "identity.verification_session.requires_input" =>
        "#/components/schemas/identity.verification_session",
      "identity.verification_session.verified" =>
        "#/components/schemas/identity.verification_session",
      "invoice.created" => "#/components/schemas/invoice",
      "invoice.deleted" => "#/components/schemas/invoice",
      "invoice.finalization_failed" => "#/components/schemas/invoice",
      "invoice.finalized" => "#/components/schemas/invoice",
      "invoice.marked_uncollectible" => "#/components/schemas/invoice",
      "invoice.overdue" => "#/components/schemas/invoice",
      "invoice.overpaid" => "#/components/schemas/invoice",
      "invoice.paid" => "#/components/schemas/invoice",
      "invoice.payment_action_required" => "#/components/schemas/invoice",
      "invoice.payment_attempt_required" => "#/components/schemas/invoice",
      "invoice.payment_failed" => "#/components/schemas/invoice",
      "invoice.payment_succeeded" => "#/components/schemas/invoice",
      "invoice.sent" => "#/components/schemas/invoice",
      "invoice.upcoming" => "#/components/schemas/invoice",
      "invoice.updated" => "#/components/schemas/invoice",
      "invoice.voided" => "#/components/schemas/invoice",
      "invoice.will_be_due" => "#/components/schemas/invoice",
      "invoice_payment.paid" => "#/components/schemas/invoice_payment",
      "invoiceitem.created" => "#/components/schemas/invoiceitem",
      "invoiceitem.deleted" => "#/components/schemas/invoiceitem",
      "issuing_authorization.created" => "#/components/schemas/issuing.authorization",
      "issuing_authorization.request" => "#/components/schemas/issuing.authorization",
      "issuing_authorization.updated" => "#/components/schemas/issuing.authorization",
      "issuing_card.created" => "#/components/schemas/issuing.card",
      "issuing_card.updated" => "#/components/schemas/issuing.card",
      "issuing_cardholder.created" => "#/components/schemas/issuing.cardholder",
      "issuing_cardholder.updated" => "#/components/schemas/issuing.cardholder",
      "issuing_dispute.closed" => "#/components/schemas/issuing.dispute",
      "issuing_dispute.created" => "#/components/schemas/issuing.dispute",
      "issuing_dispute.funds_reinstated" => "#/components/schemas/issuing.dispute",
      "issuing_dispute.funds_rescinded" => "#/components/schemas/issuing.dispute",
      "issuing_dispute.submitted" => "#/components/schemas/issuing.dispute",
      "issuing_dispute.updated" => "#/components/schemas/issuing.dispute",
      "issuing_personalization_design.activated" =>
        "#/components/schemas/issuing.personalization_design",
      "issuing_personalization_design.deactivated" =>
        "#/components/schemas/issuing.personalization_design",
      "issuing_personalization_design.rejected" =>
        "#/components/schemas/issuing.personalization_design",
      "issuing_personalization_design.updated" =>
        "#/components/schemas/issuing.personalization_design",
      "issuing_token.created" => "#/components/schemas/issuing.token",
      "issuing_token.updated" => "#/components/schemas/issuing.token",
      "issuing_transaction.created" => "#/components/schemas/issuing.transaction",
      "issuing_transaction.purchase_details_receipt_updated" =>
        "#/components/schemas/issuing.transaction",
      "issuing_transaction.updated" => "#/components/schemas/issuing.transaction",
      "mandate.updated" => "#/components/schemas/mandate",
      "payment_intent.amount_capturable_updated" => "#/components/schemas/payment_intent",
      "payment_intent.canceled" => "#/components/schemas/payment_intent",
      "payment_intent.created" => "#/components/schemas/payment_intent",
      "payment_intent.partially_funded" => "#/components/schemas/payment_intent",
      "payment_intent.payment_failed" => "#/components/schemas/payment_intent",
      "payment_intent.processing" => "#/components/schemas/payment_intent",
      "payment_intent.requires_action" => "#/components/schemas/payment_intent",
      "payment_intent.succeeded" => "#/components/schemas/payment_intent",
      "payment_link.created" => "#/components/schemas/payment_link",
      "payment_link.updated" => "#/components/schemas/payment_link",
      "payment_method.attached" => "#/components/schemas/payment_method",
      "payment_method.automatically_updated" => "#/components/schemas/payment_method",
      "payment_method.detached" => "#/components/schemas/payment_method",
      "payment_method.updated" => "#/components/schemas/payment_method",
      "payout.canceled" => "#/components/schemas/payout",
      "payout.created" => "#/components/schemas/payout",
      "payout.failed" => "#/components/schemas/payout",
      "payout.paid" => "#/components/schemas/payout",
      "payout.reconciliation_completed" => "#/components/schemas/payout",
      "payout.updated" => "#/components/schemas/payout",
      "person.created" => "#/components/schemas/person",
      "person.deleted" => "#/components/schemas/person",
      "person.updated" => "#/components/schemas/person",
      "plan.created" => "#/components/schemas/plan",
      "plan.deleted" => "#/components/schemas/plan",
      "plan.updated" => "#/components/schemas/plan",
      "price.created" => "#/components/schemas/price",
      "price.deleted" => "#/components/schemas/price",
      "price.updated" => "#/components/schemas/price",
      "product.created" => "#/components/schemas/product",
      "product.deleted" => "#/components/schemas/product",
      "product.updated" => "#/components/schemas/product",
      "promotion_code.created" => "#/components/schemas/promotion_code",
      "promotion_code.updated" => "#/components/schemas/promotion_code",
      "quote.accepted" => "#/components/schemas/quote",
      "quote.canceled" => "#/components/schemas/quote",
      "quote.created" => "#/components/schemas/quote",
      "quote.finalized" => "#/components/schemas/quote",
      "radar.early_fraud_warning.created" => "#/components/schemas/radar.early_fraud_warning",
      "radar.early_fraud_warning.updated" => "#/components/schemas/radar.early_fraud_warning",
      "refund.created" => "#/components/schemas/refund",
      "refund.failed" => "#/components/schemas/refund",
      "refund.updated" => "#/components/schemas/refund",
      "reporting.report_run.failed" => "#/components/schemas/reporting.report_run",
      "reporting.report_run.succeeded" => "#/components/schemas/reporting.report_run",
      "reporting.report_type.updated" => "#/components/schemas/reporting.report_type",
      "reserve.hold.created" => "#/components/schemas/reserve.hold",
      "reserve.hold.updated" => "#/components/schemas/reserve.hold",
      "reserve.plan.created" => "#/components/schemas/reserve.plan",
      "reserve.plan.disabled" => "#/components/schemas/reserve.plan",
      "reserve.plan.expired" => "#/components/schemas/reserve.plan",
      "reserve.plan.updated" => "#/components/schemas/reserve.plan",
      "reserve.release.created" => "#/components/schemas/reserve.release",
      "review.closed" => "#/components/schemas/review",
      "review.opened" => "#/components/schemas/review",
      "setup_intent.canceled" => "#/components/schemas/setup_intent",
      "setup_intent.created" => "#/components/schemas/setup_intent",
      "setup_intent.requires_action" => "#/components/schemas/setup_intent",
      "setup_intent.setup_failed" => "#/components/schemas/setup_intent",
      "setup_intent.succeeded" => "#/components/schemas/setup_intent",
      "sigma.scheduled_query_run.created" => "#/components/schemas/scheduled_query_run",
      "source.canceled" => "#/components/schemas/source",
      "source.chargeable" => "#/components/schemas/source",
      "source.failed" => "#/components/schemas/source",
      "source.mandate_notification" => "#/components/schemas/source_mandate_notification",
      "source.refund_attributes_required" => "#/components/schemas/source",
      "source.transaction.created" => "#/components/schemas/source_transaction",
      "source.transaction.updated" => "#/components/schemas/source_transaction",
      "subscription_schedule.aborted" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.canceled" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.completed" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.created" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.expiring" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.released" => "#/components/schemas/subscription_schedule",
      "subscription_schedule.updated" => "#/components/schemas/subscription_schedule",
      "tax.settings.updated" => "#/components/schemas/tax.settings",
      "tax_rate.created" => "#/components/schemas/tax_rate",
      "tax_rate.updated" => "#/components/schemas/tax_rate",
      "terminal.reader.action_failed" => "#/components/schemas/terminal.reader",
      "terminal.reader.action_succeeded" => "#/components/schemas/terminal.reader",
      "terminal.reader.action_updated" => "#/components/schemas/terminal.reader",
      "test_helpers.test_clock.advancing" => "#/components/schemas/test_helpers.test_clock",
      "test_helpers.test_clock.created" => "#/components/schemas/test_helpers.test_clock",
      "test_helpers.test_clock.deleted" => "#/components/schemas/test_helpers.test_clock",
      "test_helpers.test_clock.internal_failure" =>
        "#/components/schemas/test_helpers.test_clock",
      "test_helpers.test_clock.ready" => "#/components/schemas/test_helpers.test_clock",
      "topup.canceled" => "#/components/schemas/topup",
      "topup.created" => "#/components/schemas/topup",
      "topup.failed" => "#/components/schemas/topup",
      "topup.reversed" => "#/components/schemas/topup",
      "topup.succeeded" => "#/components/schemas/topup",
      "transfer.created" => "#/components/schemas/transfer",
      "transfer.reversed" => "#/components/schemas/transfer",
      "transfer.updated" => "#/components/schemas/transfer",
      "treasury.credit_reversal.created" => "#/components/schemas/treasury.credit_reversal",
      "treasury.credit_reversal.posted" => "#/components/schemas/treasury.credit_reversal",
      "treasury.debit_reversal.completed" => "#/components/schemas/treasury.debit_reversal",
      "treasury.debit_reversal.created" => "#/components/schemas/treasury.debit_reversal",
      "treasury.debit_reversal.initial_credit_granted" =>
        "#/components/schemas/treasury.debit_reversal",
      "treasury.financial_account.closed" => "#/components/schemas/treasury.financial_account",
      "treasury.financial_account.created" => "#/components/schemas/treasury.financial_account",
      "treasury.financial_account.features_status_updated" =>
        "#/components/schemas/treasury.financial_account",
      "treasury.inbound_transfer.canceled" => "#/components/schemas/treasury.inbound_transfer",
      "treasury.inbound_transfer.created" => "#/components/schemas/treasury.inbound_transfer",
      "treasury.inbound_transfer.failed" => "#/components/schemas/treasury.inbound_transfer",
      "treasury.inbound_transfer.succeeded" => "#/components/schemas/treasury.inbound_transfer",
      "treasury.outbound_payment.canceled" => "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.created" => "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.expected_arrival_date_updated" =>
        "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.failed" => "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.posted" => "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.returned" => "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_payment.tracking_details_updated" =>
        "#/components/schemas/treasury.outbound_payment",
      "treasury.outbound_transfer.canceled" => "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.created" => "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.expected_arrival_date_updated" =>
        "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.failed" => "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.posted" => "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.returned" => "#/components/schemas/treasury.outbound_transfer",
      "treasury.outbound_transfer.tracking_details_updated" =>
        "#/components/schemas/treasury.outbound_transfer",
      "treasury.received_credit.created" => "#/components/schemas/treasury.received_credit",
      "treasury.received_credit.failed" => "#/components/schemas/treasury.received_credit",
      "treasury.received_credit.succeeded" => "#/components/schemas/treasury.received_credit",
      "treasury.received_debit.created" => "#/components/schemas/treasury.received_debit",
      "v1.account.application.authorized" => nil,
      "v1.account.application.deauthorized" => nil,
      "v1.account.external_account.created" => nil,
      "v1.account.external_account.deleted" => nil,
      "v1.account.external_account.updated" => nil,
      "v1.account.updated" => nil,
      "v1.application_fee.created" => nil,
      "v1.application_fee.refund.updated" => nil,
      "v1.application_fee.refunded" => nil,
      "v1.balance.available" => nil,
      "v1.balance_settings.updated" => nil,
      "v1.billing.alert.triggered" => nil,
      "v1.billing.credit_balance_transaction.created" => nil,
      "v1.billing.credit_grant.created" => nil,
      "v1.billing.credit_grant.updated" => nil,
      "v1.billing.meter.created" => nil,
      "v1.billing.meter.deactivated" => nil,
      "v1.billing.meter.error_report_triggered" => nil,
      "v1.billing.meter.no_meter_found" => nil,
      "v1.billing.meter.reactivated" => nil,
      "v1.billing.meter.updated" => nil,
      "v1.billing_portal.configuration.created" => nil,
      "v1.billing_portal.configuration.updated" => nil,
      "v1.billing_portal.session.created" => nil,
      "v1.capability.updated" => nil,
      "v1.cash_balance.funds_available" => nil,
      "v1.charge.captured" => nil,
      "v1.charge.dispute.closed" => nil,
      "v1.charge.dispute.created" => nil,
      "v1.charge.dispute.funds_reinstated" => nil,
      "v1.charge.dispute.funds_withdrawn" => nil,
      "v1.charge.dispute.updated" => nil,
      "v1.charge.expired" => nil,
      "v1.charge.failed" => nil,
      "v1.charge.pending" => nil,
      "v1.charge.refund.updated" => nil,
      "v1.charge.refunded" => nil,
      "v1.charge.succeeded" => nil,
      "v1.charge.updated" => nil,
      "v1.checkout.session.async_payment_failed" => nil,
      "v1.checkout.session.async_payment_succeeded" => nil,
      "v1.checkout.session.completed" => nil,
      "v1.checkout.session.expired" => nil,
      "v1.climate.order.canceled" => nil,
      "v1.climate.order.created" => nil,
      "v1.climate.order.delayed" => nil,
      "v1.climate.order.delivered" => nil,
      "v1.climate.order.product_substituted" => nil,
      "v1.climate.product.created" => nil,
      "v1.climate.product.pricing_updated" => nil,
      "v1.coupon.created" => nil,
      "v1.coupon.deleted" => nil,
      "v1.coupon.updated" => nil,
      "v1.credit_note.created" => nil,
      "v1.credit_note.updated" => nil,
      "v1.credit_note.voided" => nil,
      "v1.customer.created" => nil,
      "v1.customer.deleted" => nil,
      "v1.customer.discount.created" => nil,
      "v1.customer.discount.deleted" => nil,
      "v1.customer.discount.updated" => nil,
      "v1.customer.subscription.created" => nil,
      "v1.customer.subscription.deleted" => nil,
      "v1.customer.subscription.paused" => nil,
      "v1.customer.subscription.pending_update_applied" => nil,
      "v1.customer.subscription.pending_update_expired" => nil,
      "v1.customer.subscription.resumed" => nil,
      "v1.customer.subscription.trial_will_end" => nil,
      "v1.customer.subscription.updated" => nil,
      "v1.customer.tax_id.created" => nil,
      "v1.customer.tax_id.deleted" => nil,
      "v1.customer.tax_id.updated" => nil,
      "v1.customer.updated" => nil,
      "v1.customer_cash_balance_transaction.created" => nil,
      "v1.entitlements.active_entitlement_summary.updated" => nil,
      "v1.file.created" => nil,
      "v1.financial_connections.account.account_numbers_updated" => nil,
      "v1.financial_connections.account.created" => nil,
      "v1.financial_connections.account.deactivated" => nil,
      "v1.financial_connections.account.disconnected" => nil,
      "v1.financial_connections.account.expected_deactivation_date_updated" => nil,
      "v1.financial_connections.account.reactivated" => nil,
      "v1.financial_connections.account.refreshed_balance" => nil,
      "v1.financial_connections.account.refreshed_ownership" => nil,
      "v1.financial_connections.account.refreshed_transactions" => nil,
      "v1.financial_connections.account.supported_payment_method_types_updated" => nil,
      "v1.financial_connections.account.upcoming_account_number_expiry" => nil,
      "v1.financial_connections.account.upcoming_deactivation" => nil,
      "v1.identity.verification_session.canceled" => nil,
      "v1.identity.verification_session.created" => nil,
      "v1.identity.verification_session.processing" => nil,
      "v1.identity.verification_session.redacted" => nil,
      "v1.identity.verification_session.requires_input" => nil,
      "v1.identity.verification_session.verified" => nil,
      "v1.invoice.created" => nil,
      "v1.invoice.deleted" => nil,
      "v1.invoice.finalization_failed" => nil,
      "v1.invoice.finalized" => nil,
      "v1.invoice.marked_uncollectible" => nil,
      "v1.invoice.overdue" => nil,
      "v1.invoice.overpaid" => nil,
      "v1.invoice.paid" => nil,
      "v1.invoice.payment_action_required" => nil,
      "v1.invoice.payment_attempt_required" => nil,
      "v1.invoice.payment_failed" => nil,
      "v1.invoice.payment_succeeded" => nil,
      "v1.invoice.sent" => nil,
      "v1.invoice.upcoming" => nil,
      "v1.invoice.updated" => nil,
      "v1.invoice.voided" => nil,
      "v1.invoice.will_be_due" => nil,
      "v1.invoice_payment.paid" => nil,
      "v1.invoiceitem.created" => nil,
      "v1.invoiceitem.deleted" => nil,
      "v1.issuing_authorization.created" => nil,
      "v1.issuing_authorization.request" => nil,
      "v1.issuing_authorization.updated" => nil,
      "v1.issuing_card.created" => nil,
      "v1.issuing_card.updated" => nil,
      "v1.issuing_cardholder.created" => nil,
      "v1.issuing_cardholder.updated" => nil,
      "v1.issuing_dispute.closed" => nil,
      "v1.issuing_dispute.created" => nil,
      "v1.issuing_dispute.funds_reinstated" => nil,
      "v1.issuing_dispute.funds_rescinded" => nil,
      "v1.issuing_dispute.submitted" => nil,
      "v1.issuing_dispute.updated" => nil,
      "v1.issuing_personalization_design.activated" => nil,
      "v1.issuing_personalization_design.deactivated" => nil,
      "v1.issuing_personalization_design.rejected" => nil,
      "v1.issuing_personalization_design.updated" => nil,
      "v1.issuing_token.created" => nil,
      "v1.issuing_token.updated" => nil,
      "v1.issuing_transaction.created" => nil,
      "v1.issuing_transaction.purchase_details_receipt_updated" => nil,
      "v1.issuing_transaction.updated" => nil,
      "v1.mandate.updated" => nil,
      "v1.payment_intent.amount_capturable_updated" => nil,
      "v1.payment_intent.canceled" => nil,
      "v1.payment_intent.created" => nil,
      "v1.payment_intent.partially_funded" => nil,
      "v1.payment_intent.payment_failed" => nil,
      "v1.payment_intent.processing" => nil,
      "v1.payment_intent.requires_action" => nil,
      "v1.payment_intent.succeeded" => nil,
      "v1.payment_link.created" => nil,
      "v1.payment_link.updated" => nil,
      "v1.payment_method.attached" => nil,
      "v1.payment_method.automatically_updated" => nil,
      "v1.payment_method.detached" => nil,
      "v1.payment_method.updated" => nil,
      "v1.payout.canceled" => nil,
      "v1.payout.created" => nil,
      "v1.payout.failed" => nil,
      "v1.payout.paid" => nil,
      "v1.payout.reconciliation_completed" => nil,
      "v1.payout.updated" => nil,
      "v1.person.created" => nil,
      "v1.person.deleted" => nil,
      "v1.person.updated" => nil,
      "v1.plan.created" => nil,
      "v1.plan.deleted" => nil,
      "v1.plan.updated" => nil,
      "v1.price.created" => nil,
      "v1.price.deleted" => nil,
      "v1.price.updated" => nil,
      "v1.product.created" => nil,
      "v1.product.deleted" => nil,
      "v1.product.updated" => nil,
      "v1.promotion_code.created" => nil,
      "v1.promotion_code.updated" => nil,
      "v1.quote.accepted" => nil,
      "v1.quote.canceled" => nil,
      "v1.quote.created" => nil,
      "v1.quote.finalized" => nil,
      "v1.radar.early_fraud_warning.created" => nil,
      "v1.radar.early_fraud_warning.updated" => nil,
      "v1.refund.created" => nil,
      "v1.refund.failed" => nil,
      "v1.refund.updated" => nil,
      "v1.review.closed" => nil,
      "v1.review.opened" => nil,
      "v1.setup_intent.canceled" => nil,
      "v1.setup_intent.created" => nil,
      "v1.setup_intent.requires_action" => nil,
      "v1.setup_intent.setup_failed" => nil,
      "v1.setup_intent.succeeded" => nil,
      "v1.sigma.scheduled_query_run.created" => nil,
      "v1.source.canceled" => nil,
      "v1.source.chargeable" => nil,
      "v1.source.failed" => nil,
      "v1.source.refund_attributes_required" => nil,
      "v1.subscription_schedule.aborted" => nil,
      "v1.subscription_schedule.canceled" => nil,
      "v1.subscription_schedule.completed" => nil,
      "v1.subscription_schedule.created" => nil,
      "v1.subscription_schedule.expiring" => nil,
      "v1.subscription_schedule.released" => nil,
      "v1.subscription_schedule.updated" => nil,
      "v1.tax.settings.updated" => nil,
      "v1.tax_rate.created" => nil,
      "v1.tax_rate.updated" => nil,
      "v1.terminal.reader.action_failed" => nil,
      "v1.terminal.reader.action_succeeded" => nil,
      "v1.terminal.reader.action_updated" => nil,
      "v1.test_helpers.test_clock.advancing" => nil,
      "v1.test_helpers.test_clock.created" => nil,
      "v1.test_helpers.test_clock.deleted" => nil,
      "v1.test_helpers.test_clock.internal_failure" => nil,
      "v1.test_helpers.test_clock.ready" => nil,
      "v1.topup.canceled" => nil,
      "v1.topup.created" => nil,
      "v1.topup.failed" => nil,
      "v1.topup.reversed" => nil,
      "v1.topup.succeeded" => nil,
      "v1.transfer.created" => nil,
      "v1.transfer.reversed" => nil,
      "v1.transfer.updated" => nil,
      "v2.commerce.product_catalog.imports.failed" => nil,
      "v2.commerce.product_catalog.imports.processing" => nil,
      "v2.commerce.product_catalog.imports.succeeded" => nil,
      "v2.commerce.product_catalog.imports.succeeded_with_errors" => nil,
      "v2.core.account.closed" => nil,
      "v2.core.account.created" => nil,
      "v2.core.account.updated" => nil,
      "v2.core.account[configuration.customer].capability_status_updated" => nil,
      "v2.core.account[configuration.customer].updated" => nil,
      "v2.core.account[configuration.merchant].capability_status_updated" => nil,
      "v2.core.account[configuration.merchant].updated" => nil,
      "v2.core.account[configuration.recipient].capability_status_updated" => nil,
      "v2.core.account[configuration.recipient].updated" => nil,
      "v2.core.account[defaults].updated" => nil,
      "v2.core.account[future_requirements].updated" => nil,
      "v2.core.account[identity].updated" => nil,
      "v2.core.account[requirements].updated" => nil,
      "v2.core.account_link.returned" => nil,
      "v2.core.account_person.created" => nil,
      "v2.core.account_person.deleted" => nil,
      "v2.core.account_person.updated" => nil,
      "v2.core.event_destination.ping" => nil
    }
  end

  @doc "Maps thin event type strings to their per-event typed module."
  def event_type_to_module do
    %{
      "v1.account.application.authorized" => Stripe.Events.V1AccountApplicationAuthorizedEvent,
      "v1.account.application.deauthorized" =>
        Stripe.Events.V1AccountApplicationDeauthorizedEvent,
      "v1.account.external_account.created" => Stripe.Events.V1AccountExternalAccountCreatedEvent,
      "v1.account.external_account.deleted" => Stripe.Events.V1AccountExternalAccountDeletedEvent,
      "v1.account.external_account.updated" => Stripe.Events.V1AccountExternalAccountUpdatedEvent,
      "v1.account.updated" => Stripe.Events.V1AccountUpdatedEvent,
      "v1.application_fee.created" => Stripe.Events.V1ApplicationFeeCreatedEvent,
      "v1.application_fee.refund.updated" => Stripe.Events.V1ApplicationFeeRefundUpdatedEvent,
      "v1.application_fee.refunded" => Stripe.Events.V1ApplicationFeeRefundedEvent,
      "v1.balance.available" => Stripe.Events.V1BalanceAvailableEvent,
      "v1.balance_settings.updated" => Stripe.Events.V1BalanceSettingsUpdatedEvent,
      "v1.billing.alert.triggered" => Stripe.Events.V1BillingAlertTriggeredEvent,
      "v1.billing.credit_balance_transaction.created" =>
        Stripe.Events.V1BillingCreditBalanceTransactionCreatedEvent,
      "v1.billing.credit_grant.created" => Stripe.Events.V1BillingCreditGrantCreatedEvent,
      "v1.billing.credit_grant.updated" => Stripe.Events.V1BillingCreditGrantUpdatedEvent,
      "v1.billing.meter.created" => Stripe.Events.V1BillingMeterCreatedEvent,
      "v1.billing.meter.deactivated" => Stripe.Events.V1BillingMeterDeactivatedEvent,
      "v1.billing.meter.error_report_triggered" =>
        Stripe.Events.V1BillingMeterErrorReportTriggeredEvent,
      "v1.billing.meter.no_meter_found" => Stripe.Events.V1BillingMeterNoMeterFoundEvent,
      "v1.billing.meter.reactivated" => Stripe.Events.V1BillingMeterReactivatedEvent,
      "v1.billing.meter.updated" => Stripe.Events.V1BillingMeterUpdatedEvent,
      "v1.billing_portal.configuration.created" =>
        Stripe.Events.V1BillingPortalConfigurationCreatedEvent,
      "v1.billing_portal.configuration.updated" =>
        Stripe.Events.V1BillingPortalConfigurationUpdatedEvent,
      "v1.billing_portal.session.created" => Stripe.Events.V1BillingPortalSessionCreatedEvent,
      "v1.capability.updated" => Stripe.Events.V1CapabilityUpdatedEvent,
      "v1.cash_balance.funds_available" => Stripe.Events.V1CashBalanceFundsAvailableEvent,
      "v1.charge.captured" => Stripe.Events.V1ChargeCapturedEvent,
      "v1.charge.dispute.closed" => Stripe.Events.V1ChargeDisputeClosedEvent,
      "v1.charge.dispute.created" => Stripe.Events.V1ChargeDisputeCreatedEvent,
      "v1.charge.dispute.funds_reinstated" => Stripe.Events.V1ChargeDisputeFundsReinstatedEvent,
      "v1.charge.dispute.funds_withdrawn" => Stripe.Events.V1ChargeDisputeFundsWithdrawnEvent,
      "v1.charge.dispute.updated" => Stripe.Events.V1ChargeDisputeUpdatedEvent,
      "v1.charge.expired" => Stripe.Events.V1ChargeExpiredEvent,
      "v1.charge.failed" => Stripe.Events.V1ChargeFailedEvent,
      "v1.charge.pending" => Stripe.Events.V1ChargePendingEvent,
      "v1.charge.refund.updated" => Stripe.Events.V1ChargeRefundUpdatedEvent,
      "v1.charge.refunded" => Stripe.Events.V1ChargeRefundedEvent,
      "v1.charge.succeeded" => Stripe.Events.V1ChargeSucceededEvent,
      "v1.charge.updated" => Stripe.Events.V1ChargeUpdatedEvent,
      "v1.checkout.session.async_payment_failed" =>
        Stripe.Events.V1CheckoutSessionAsyncPaymentFailedEvent,
      "v1.checkout.session.async_payment_succeeded" =>
        Stripe.Events.V1CheckoutSessionAsyncPaymentSucceededEvent,
      "v1.checkout.session.completed" => Stripe.Events.V1CheckoutSessionCompletedEvent,
      "v1.checkout.session.expired" => Stripe.Events.V1CheckoutSessionExpiredEvent,
      "v1.climate.order.canceled" => Stripe.Events.V1ClimateOrderCanceledEvent,
      "v1.climate.order.created" => Stripe.Events.V1ClimateOrderCreatedEvent,
      "v1.climate.order.delayed" => Stripe.Events.V1ClimateOrderDelayedEvent,
      "v1.climate.order.delivered" => Stripe.Events.V1ClimateOrderDeliveredEvent,
      "v1.climate.order.product_substituted" =>
        Stripe.Events.V1ClimateOrderProductSubstitutedEvent,
      "v1.climate.product.created" => Stripe.Events.V1ClimateProductCreatedEvent,
      "v1.climate.product.pricing_updated" => Stripe.Events.V1ClimateProductPricingUpdatedEvent,
      "v1.coupon.created" => Stripe.Events.V1CouponCreatedEvent,
      "v1.coupon.deleted" => Stripe.Events.V1CouponDeletedEvent,
      "v1.coupon.updated" => Stripe.Events.V1CouponUpdatedEvent,
      "v1.credit_note.created" => Stripe.Events.V1CreditNoteCreatedEvent,
      "v1.credit_note.updated" => Stripe.Events.V1CreditNoteUpdatedEvent,
      "v1.credit_note.voided" => Stripe.Events.V1CreditNoteVoidedEvent,
      "v1.customer.created" => Stripe.Events.V1CustomerCreatedEvent,
      "v1.customer.deleted" => Stripe.Events.V1CustomerDeletedEvent,
      "v1.customer.discount.created" => Stripe.Events.V1CustomerDiscountCreatedEvent,
      "v1.customer.discount.deleted" => Stripe.Events.V1CustomerDiscountDeletedEvent,
      "v1.customer.discount.updated" => Stripe.Events.V1CustomerDiscountUpdatedEvent,
      "v1.customer.subscription.created" => Stripe.Events.V1CustomerSubscriptionCreatedEvent,
      "v1.customer.subscription.deleted" => Stripe.Events.V1CustomerSubscriptionDeletedEvent,
      "v1.customer.subscription.paused" => Stripe.Events.V1CustomerSubscriptionPausedEvent,
      "v1.customer.subscription.pending_update_applied" =>
        Stripe.Events.V1CustomerSubscriptionPendingUpdateAppliedEvent,
      "v1.customer.subscription.pending_update_expired" =>
        Stripe.Events.V1CustomerSubscriptionPendingUpdateExpiredEvent,
      "v1.customer.subscription.resumed" => Stripe.Events.V1CustomerSubscriptionResumedEvent,
      "v1.customer.subscription.trial_will_end" =>
        Stripe.Events.V1CustomerSubscriptionTrialWillEndEvent,
      "v1.customer.subscription.updated" => Stripe.Events.V1CustomerSubscriptionUpdatedEvent,
      "v1.customer.tax_id.created" => Stripe.Events.V1CustomerTaxIdCreatedEvent,
      "v1.customer.tax_id.deleted" => Stripe.Events.V1CustomerTaxIdDeletedEvent,
      "v1.customer.tax_id.updated" => Stripe.Events.V1CustomerTaxIdUpdatedEvent,
      "v1.customer.updated" => Stripe.Events.V1CustomerUpdatedEvent,
      "v1.customer_cash_balance_transaction.created" =>
        Stripe.Events.V1CustomerCashBalanceTransactionCreatedEvent,
      "v1.entitlements.active_entitlement_summary.updated" =>
        Stripe.Events.V1EntitlementsActiveEntitlementSummaryUpdatedEvent,
      "v1.file.created" => Stripe.Events.V1FileCreatedEvent,
      "v1.financial_connections.account.account_numbers_updated" =>
        Stripe.Events.V1FinancialConnectionsAccountAccountNumbersUpdatedEvent,
      "v1.financial_connections.account.created" =>
        Stripe.Events.V1FinancialConnectionsAccountCreatedEvent,
      "v1.financial_connections.account.deactivated" =>
        Stripe.Events.V1FinancialConnectionsAccountDeactivatedEvent,
      "v1.financial_connections.account.disconnected" =>
        Stripe.Events.V1FinancialConnectionsAccountDisconnectedEvent,
      "v1.financial_connections.account.expected_deactivation_date_updated" =>
        Stripe.Events.V1FinancialConnectionsAccountExpectedDeactivationDateUpdatedEvent,
      "v1.financial_connections.account.reactivated" =>
        Stripe.Events.V1FinancialConnectionsAccountReactivatedEvent,
      "v1.financial_connections.account.refreshed_balance" =>
        Stripe.Events.V1FinancialConnectionsAccountRefreshedBalanceEvent,
      "v1.financial_connections.account.refreshed_ownership" =>
        Stripe.Events.V1FinancialConnectionsAccountRefreshedOwnershipEvent,
      "v1.financial_connections.account.refreshed_transactions" =>
        Stripe.Events.V1FinancialConnectionsAccountRefreshedTransactionsEvent,
      "v1.financial_connections.account.supported_payment_method_types_updated" =>
        Stripe.Events.V1FinancialConnectionsAccountSupportedPaymentMethodTypesUpdatedEvent,
      "v1.financial_connections.account.upcoming_account_number_expiry" =>
        Stripe.Events.V1FinancialConnectionsAccountUpcomingAccountNumberExpiryEvent,
      "v1.financial_connections.account.upcoming_deactivation" =>
        Stripe.Events.V1FinancialConnectionsAccountUpcomingDeactivationEvent,
      "v1.identity.verification_session.canceled" =>
        Stripe.Events.V1IdentityVerificationSessionCanceledEvent,
      "v1.identity.verification_session.created" =>
        Stripe.Events.V1IdentityVerificationSessionCreatedEvent,
      "v1.identity.verification_session.processing" =>
        Stripe.Events.V1IdentityVerificationSessionProcessingEvent,
      "v1.identity.verification_session.redacted" =>
        Stripe.Events.V1IdentityVerificationSessionRedactedEvent,
      "v1.identity.verification_session.requires_input" =>
        Stripe.Events.V1IdentityVerificationSessionRequiresInputEvent,
      "v1.identity.verification_session.verified" =>
        Stripe.Events.V1IdentityVerificationSessionVerifiedEvent,
      "v1.invoice.created" => Stripe.Events.V1InvoiceCreatedEvent,
      "v1.invoice.deleted" => Stripe.Events.V1InvoiceDeletedEvent,
      "v1.invoice.finalization_failed" => Stripe.Events.V1InvoiceFinalizationFailedEvent,
      "v1.invoice.finalized" => Stripe.Events.V1InvoiceFinalizedEvent,
      "v1.invoice.marked_uncollectible" => Stripe.Events.V1InvoiceMarkedUncollectibleEvent,
      "v1.invoice.overdue" => Stripe.Events.V1InvoiceOverdueEvent,
      "v1.invoice.overpaid" => Stripe.Events.V1InvoiceOverpaidEvent,
      "v1.invoice.paid" => Stripe.Events.V1InvoicePaidEvent,
      "v1.invoice.payment_action_required" => Stripe.Events.V1InvoicePaymentActionRequiredEvent,
      "v1.invoice.payment_attempt_required" => Stripe.Events.V1InvoicePaymentAttemptRequiredEvent,
      "v1.invoice.payment_failed" => Stripe.Events.V1InvoicePaymentFailedEvent,
      "v1.invoice.payment_succeeded" => Stripe.Events.V1InvoicePaymentSucceededEvent,
      "v1.invoice.sent" => Stripe.Events.V1InvoiceSentEvent,
      "v1.invoice.upcoming" => Stripe.Events.V1InvoiceUpcomingEvent,
      "v1.invoice.updated" => Stripe.Events.V1InvoiceUpdatedEvent,
      "v1.invoice.voided" => Stripe.Events.V1InvoiceVoidedEvent,
      "v1.invoice.will_be_due" => Stripe.Events.V1InvoiceWillBeDueEvent,
      "v1.invoice_payment.paid" => Stripe.Events.V1InvoicePaymentPaidEvent,
      "v1.invoiceitem.created" => Stripe.Events.V1InvoiceitemCreatedEvent,
      "v1.invoiceitem.deleted" => Stripe.Events.V1InvoiceitemDeletedEvent,
      "v1.issuing_authorization.created" => Stripe.Events.V1IssuingAuthorizationCreatedEvent,
      "v1.issuing_authorization.request" => Stripe.Events.V1IssuingAuthorizationRequestEvent,
      "v1.issuing_authorization.updated" => Stripe.Events.V1IssuingAuthorizationUpdatedEvent,
      "v1.issuing_card.created" => Stripe.Events.V1IssuingCardCreatedEvent,
      "v1.issuing_card.updated" => Stripe.Events.V1IssuingCardUpdatedEvent,
      "v1.issuing_cardholder.created" => Stripe.Events.V1IssuingCardholderCreatedEvent,
      "v1.issuing_cardholder.updated" => Stripe.Events.V1IssuingCardholderUpdatedEvent,
      "v1.issuing_dispute.closed" => Stripe.Events.V1IssuingDisputeClosedEvent,
      "v1.issuing_dispute.created" => Stripe.Events.V1IssuingDisputeCreatedEvent,
      "v1.issuing_dispute.funds_reinstated" => Stripe.Events.V1IssuingDisputeFundsReinstatedEvent,
      "v1.issuing_dispute.funds_rescinded" => Stripe.Events.V1IssuingDisputeFundsRescindedEvent,
      "v1.issuing_dispute.submitted" => Stripe.Events.V1IssuingDisputeSubmittedEvent,
      "v1.issuing_dispute.updated" => Stripe.Events.V1IssuingDisputeUpdatedEvent,
      "v1.issuing_personalization_design.activated" =>
        Stripe.Events.V1IssuingPersonalizationDesignActivatedEvent,
      "v1.issuing_personalization_design.deactivated" =>
        Stripe.Events.V1IssuingPersonalizationDesignDeactivatedEvent,
      "v1.issuing_personalization_design.rejected" =>
        Stripe.Events.V1IssuingPersonalizationDesignRejectedEvent,
      "v1.issuing_personalization_design.updated" =>
        Stripe.Events.V1IssuingPersonalizationDesignUpdatedEvent,
      "v1.issuing_token.created" => Stripe.Events.V1IssuingTokenCreatedEvent,
      "v1.issuing_token.updated" => Stripe.Events.V1IssuingTokenUpdatedEvent,
      "v1.issuing_transaction.created" => Stripe.Events.V1IssuingTransactionCreatedEvent,
      "v1.issuing_transaction.purchase_details_receipt_updated" =>
        Stripe.Events.V1IssuingTransactionPurchaseDetailsReceiptUpdatedEvent,
      "v1.issuing_transaction.updated" => Stripe.Events.V1IssuingTransactionUpdatedEvent,
      "v1.mandate.updated" => Stripe.Events.V1MandateUpdatedEvent,
      "v1.payment_intent.amount_capturable_updated" =>
        Stripe.Events.V1PaymentIntentAmountCapturableUpdatedEvent,
      "v1.payment_intent.canceled" => Stripe.Events.V1PaymentIntentCanceledEvent,
      "v1.payment_intent.created" => Stripe.Events.V1PaymentIntentCreatedEvent,
      "v1.payment_intent.partially_funded" => Stripe.Events.V1PaymentIntentPartiallyFundedEvent,
      "v1.payment_intent.payment_failed" => Stripe.Events.V1PaymentIntentPaymentFailedEvent,
      "v1.payment_intent.processing" => Stripe.Events.V1PaymentIntentProcessingEvent,
      "v1.payment_intent.requires_action" => Stripe.Events.V1PaymentIntentRequiresActionEvent,
      "v1.payment_intent.succeeded" => Stripe.Events.V1PaymentIntentSucceededEvent,
      "v1.payment_link.created" => Stripe.Events.V1PaymentLinkCreatedEvent,
      "v1.payment_link.updated" => Stripe.Events.V1PaymentLinkUpdatedEvent,
      "v1.payment_method.attached" => Stripe.Events.V1PaymentMethodAttachedEvent,
      "v1.payment_method.automatically_updated" =>
        Stripe.Events.V1PaymentMethodAutomaticallyUpdatedEvent,
      "v1.payment_method.detached" => Stripe.Events.V1PaymentMethodDetachedEvent,
      "v1.payment_method.updated" => Stripe.Events.V1PaymentMethodUpdatedEvent,
      "v1.payout.canceled" => Stripe.Events.V1PayoutCanceledEvent,
      "v1.payout.created" => Stripe.Events.V1PayoutCreatedEvent,
      "v1.payout.failed" => Stripe.Events.V1PayoutFailedEvent,
      "v1.payout.paid" => Stripe.Events.V1PayoutPaidEvent,
      "v1.payout.reconciliation_completed" => Stripe.Events.V1PayoutReconciliationCompletedEvent,
      "v1.payout.updated" => Stripe.Events.V1PayoutUpdatedEvent,
      "v1.person.created" => Stripe.Events.V1PersonCreatedEvent,
      "v1.person.deleted" => Stripe.Events.V1PersonDeletedEvent,
      "v1.person.updated" => Stripe.Events.V1PersonUpdatedEvent,
      "v1.plan.created" => Stripe.Events.V1PlanCreatedEvent,
      "v1.plan.deleted" => Stripe.Events.V1PlanDeletedEvent,
      "v1.plan.updated" => Stripe.Events.V1PlanUpdatedEvent,
      "v1.price.created" => Stripe.Events.V1PriceCreatedEvent,
      "v1.price.deleted" => Stripe.Events.V1PriceDeletedEvent,
      "v1.price.updated" => Stripe.Events.V1PriceUpdatedEvent,
      "v1.product.created" => Stripe.Events.V1ProductCreatedEvent,
      "v1.product.deleted" => Stripe.Events.V1ProductDeletedEvent,
      "v1.product.updated" => Stripe.Events.V1ProductUpdatedEvent,
      "v1.promotion_code.created" => Stripe.Events.V1PromotionCodeCreatedEvent,
      "v1.promotion_code.updated" => Stripe.Events.V1PromotionCodeUpdatedEvent,
      "v1.quote.accepted" => Stripe.Events.V1QuoteAcceptedEvent,
      "v1.quote.canceled" => Stripe.Events.V1QuoteCanceledEvent,
      "v1.quote.created" => Stripe.Events.V1QuoteCreatedEvent,
      "v1.quote.finalized" => Stripe.Events.V1QuoteFinalizedEvent,
      "v1.radar.early_fraud_warning.created" =>
        Stripe.Events.V1RadarEarlyFraudWarningCreatedEvent,
      "v1.radar.early_fraud_warning.updated" =>
        Stripe.Events.V1RadarEarlyFraudWarningUpdatedEvent,
      "v1.refund.created" => Stripe.Events.V1RefundCreatedEvent,
      "v1.refund.failed" => Stripe.Events.V1RefundFailedEvent,
      "v1.refund.updated" => Stripe.Events.V1RefundUpdatedEvent,
      "v1.review.closed" => Stripe.Events.V1ReviewClosedEvent,
      "v1.review.opened" => Stripe.Events.V1ReviewOpenedEvent,
      "v1.setup_intent.canceled" => Stripe.Events.V1SetupIntentCanceledEvent,
      "v1.setup_intent.created" => Stripe.Events.V1SetupIntentCreatedEvent,
      "v1.setup_intent.requires_action" => Stripe.Events.V1SetupIntentRequiresActionEvent,
      "v1.setup_intent.setup_failed" => Stripe.Events.V1SetupIntentSetupFailedEvent,
      "v1.setup_intent.succeeded" => Stripe.Events.V1SetupIntentSucceededEvent,
      "v1.sigma.scheduled_query_run.created" =>
        Stripe.Events.V1SigmaScheduledQueryRunCreatedEvent,
      "v1.source.canceled" => Stripe.Events.V1SourceCanceledEvent,
      "v1.source.chargeable" => Stripe.Events.V1SourceChargeableEvent,
      "v1.source.failed" => Stripe.Events.V1SourceFailedEvent,
      "v1.source.refund_attributes_required" =>
        Stripe.Events.V1SourceRefundAttributesRequiredEvent,
      "v1.subscription_schedule.aborted" => Stripe.Events.V1SubscriptionScheduleAbortedEvent,
      "v1.subscription_schedule.canceled" => Stripe.Events.V1SubscriptionScheduleCanceledEvent,
      "v1.subscription_schedule.completed" => Stripe.Events.V1SubscriptionScheduleCompletedEvent,
      "v1.subscription_schedule.created" => Stripe.Events.V1SubscriptionScheduleCreatedEvent,
      "v1.subscription_schedule.expiring" => Stripe.Events.V1SubscriptionScheduleExpiringEvent,
      "v1.subscription_schedule.released" => Stripe.Events.V1SubscriptionScheduleReleasedEvent,
      "v1.subscription_schedule.updated" => Stripe.Events.V1SubscriptionScheduleUpdatedEvent,
      "v1.tax.settings.updated" => Stripe.Events.V1TaxSettingsUpdatedEvent,
      "v1.tax_rate.created" => Stripe.Events.V1TaxRateCreatedEvent,
      "v1.tax_rate.updated" => Stripe.Events.V1TaxRateUpdatedEvent,
      "v1.terminal.reader.action_failed" => Stripe.Events.V1TerminalReaderActionFailedEvent,
      "v1.terminal.reader.action_succeeded" => Stripe.Events.V1TerminalReaderActionSucceededEvent,
      "v1.terminal.reader.action_updated" => Stripe.Events.V1TerminalReaderActionUpdatedEvent,
      "v1.test_helpers.test_clock.advancing" =>
        Stripe.Events.V1TestHelpersTestClockAdvancingEvent,
      "v1.test_helpers.test_clock.created" => Stripe.Events.V1TestHelpersTestClockCreatedEvent,
      "v1.test_helpers.test_clock.deleted" => Stripe.Events.V1TestHelpersTestClockDeletedEvent,
      "v1.test_helpers.test_clock.internal_failure" =>
        Stripe.Events.V1TestHelpersTestClockInternalFailureEvent,
      "v1.test_helpers.test_clock.ready" => Stripe.Events.V1TestHelpersTestClockReadyEvent,
      "v1.topup.canceled" => Stripe.Events.V1TopupCanceledEvent,
      "v1.topup.created" => Stripe.Events.V1TopupCreatedEvent,
      "v1.topup.failed" => Stripe.Events.V1TopupFailedEvent,
      "v1.topup.reversed" => Stripe.Events.V1TopupReversedEvent,
      "v1.topup.succeeded" => Stripe.Events.V1TopupSucceededEvent,
      "v1.transfer.created" => Stripe.Events.V1TransferCreatedEvent,
      "v1.transfer.reversed" => Stripe.Events.V1TransferReversedEvent,
      "v1.transfer.updated" => Stripe.Events.V1TransferUpdatedEvent,
      "v2.commerce.product_catalog.imports.failed" =>
        Stripe.Events.V2CommerceProductCatalogImportsFailedEvent,
      "v2.commerce.product_catalog.imports.processing" =>
        Stripe.Events.V2CommerceProductCatalogImportsProcessingEvent,
      "v2.commerce.product_catalog.imports.succeeded" =>
        Stripe.Events.V2CommerceProductCatalogImportsSucceededEvent,
      "v2.commerce.product_catalog.imports.succeeded_with_errors" =>
        Stripe.Events.V2CommerceProductCatalogImportsSucceededWithErrorsEvent,
      "v2.core.account.closed" => Stripe.Events.V2CoreAccountClosedEvent,
      "v2.core.account.created" => Stripe.Events.V2CoreAccountCreatedEvent,
      "v2.core.account.updated" => Stripe.Events.V2CoreAccountUpdatedEvent,
      "v2.core.account[configuration.customer].capability_status_updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationCustomerCapabilityStatusUpdatedEvent,
      "v2.core.account[configuration.customer].updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationCustomerUpdatedEvent,
      "v2.core.account[configuration.merchant].capability_status_updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationMerchantCapabilityStatusUpdatedEvent,
      "v2.core.account[configuration.merchant].updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationMerchantUpdatedEvent,
      "v2.core.account[configuration.recipient].capability_status_updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationRecipientCapabilityStatusUpdatedEvent,
      "v2.core.account[configuration.recipient].updated" =>
        Stripe.Events.V2CoreAccountIncludingConfigurationRecipientUpdatedEvent,
      "v2.core.account[defaults].updated" =>
        Stripe.Events.V2CoreAccountIncludingDefaultsUpdatedEvent,
      "v2.core.account[future_requirements].updated" =>
        Stripe.Events.V2CoreAccountIncludingFutureRequirementsUpdatedEvent,
      "v2.core.account[identity].updated" =>
        Stripe.Events.V2CoreAccountIncludingIdentityUpdatedEvent,
      "v2.core.account[requirements].updated" =>
        Stripe.Events.V2CoreAccountIncludingRequirementsUpdatedEvent,
      "v2.core.account_link.returned" => Stripe.Events.V2CoreAccountLinkReturnedEvent,
      "v2.core.account_person.created" => Stripe.Events.V2CoreAccountPersonCreatedEvent,
      "v2.core.account_person.deleted" => Stripe.Events.V2CoreAccountPersonDeletedEvent,
      "v2.core.account_person.updated" => Stripe.Events.V2CoreAccountPersonUpdatedEvent,
      "v2.core.event_destination.ping" => Stripe.Events.V2CoreEventDestinationPingEvent
    }
  end
end
