# File generated from our OpenAPI spec
defmodule Stripe.Resources.CardPresent do
  @moduledoc """
  setup_attempt_payment_method_details_card_present
  """

  @typedoc """
  * `generated_card` - The ID of the Card PaymentMethod which was generated by this SetupAttempt. Nullable. Expandable.
  * `offline` - Details about payments collected offline. Nullable. Expandable.
  """
  @type t :: %__MODULE__{}

  defstruct [:generated_card, :offline]

  @object_name "setup_attempt_payment_method_details_card_present"
  def object_name, do: @object_name

  def expandable_fields, do: ["generated_card", "offline"]

  def __nested_fields__ do
    %{
      "offline" => {:resource, Stripe.Resources.Offline}
    }
  end
end
