# File generated from our OpenAPI spec
defmodule Stripe.Resources.PaymentIntent do
  @moduledoc """
  PaymentIntent

  A PaymentIntent guides you through the process of collecting a payment from your customer.
  We recommend that you create exactly one PaymentIntent for each order or
  customer session in your system. You can reference the PaymentIntent later to
  see the history of payment attempts for a particular session.

  A PaymentIntent transitions through
  [multiple statuses](https://stripe.com/payments/paymentintents/lifecycle)
  throughout its lifetime as it interfaces with Stripe.js to perform
  authentication flows and ultimately creates at most one successful charge.

  Related guide: [Payment Intents API](https://docs.stripe.com/payments/payment-intents)
  """

  @typedoc """
  * `allowed_payment_method_types` - The list of payment method types allowed for use with this payment. Stripe automatically returns compatible payment methods from this list in the `payment_method_types` field of the response, based on the other PaymentIntent parameters, such as `currency`, `amount`, and `customer`. Nullable.
  * `amount` - Amount intended to be collected by this PaymentIntent. A positive integer representing how much to charge in the [smallest currency unit](https://docs.stripe.com/currencies#zero-decimal) (e.g., 100 cents to charge $1.00 or 100 to charge ¥100, a zero-decimal currency). The minimum amount is $0.50 US or [equivalent in charge currency](https://docs.stripe.com/currencies#minimum-and-maximum-charge-amounts). The amount value supports up to eight digits (e.g., a value of 99999999 for a USD charge of $999,999.99).
  * `amount_capturable` - Amount that can be captured from this PaymentIntent.
  * `amount_details` - Expandable.
  * `amount_received` - Amount that this PaymentIntent collects.
  * `application` - ID of the Connect application that created the PaymentIntent. Nullable. Expandable.
  * `application_fee_amount` - The amount of the application fee (if any) that will be requested to be applied to the payment and transferred to the application owner's Stripe account. The amount of the application fee collected will be capped at the total amount captured. For more information, see the PaymentIntents [use case for connected accounts](https://docs.stripe.com/payments/connected-accounts). Nullable.
  * `automatic_payment_methods` - Settings to configure compatible payment methods from the [Stripe Dashboard](https://dashboard.stripe.com/settings/payment_methods) Nullable. Expandable.
  * `canceled_at` - Populated when `status` is `canceled`, this is the time at which the PaymentIntent was canceled. Measured in seconds since the Unix epoch. Format: Unix timestamp. Nullable.
  * `cancellation_reason` - Reason for cancellation of this PaymentIntent, either user-provided (`duplicate`, `fraudulent`, `requested_by_customer`, or `abandoned`) or generated by Stripe internally (`failed_invoice`, `void_invoice`, `automatic`, or `expired`). Possible values: `abandoned`, `automatic`, `duplicate`, `expired`, `failed_invoice`, `fraudulent`, `requested_by_customer`, `void_invoice`. Nullable.
  * `capture_method` - Controls when the funds will be captured from the customer's account. Possible values: `automatic`, `automatic_async`, `manual`.
  * `client_secret` - The client secret of this PaymentIntent. Used for client-side retrieval using a publishable key. 

  The client secret can be used to complete a payment from your frontend. It should not be stored, logged, or exposed to anyone other than the customer. Make sure that you have TLS enabled on any page that includes the client secret.

  Refer to our docs to [accept a payment](https://docs.stripe.com/payments/accept-a-payment?ui=elements) and learn about how `client_secret` should be handled. Max length: 5000. Nullable.
  * `confirmation_method` - Describes whether we can confirm this PaymentIntent automatically, or if it requires customer action to confirm the payment. Possible values: `automatic`, `manual`.
  * `created` - Time at which the object was created. Measured in seconds since the Unix epoch. Format: Unix timestamp.
  * `currency` - Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies). Format: ISO 4217 currency code.
  * `customer` - ID of the Customer this PaymentIntent belongs to, if one exists.

  Payment methods attached to other Customers cannot be used with this PaymentIntent.

  If [setup_future_usage](https://api.stripe.com#payment_intent_object-setup_future_usage) is set and this PaymentIntent's payment method is not `card_present`, then the payment method attaches to the Customer after the PaymentIntent has been confirmed and any required actions from the user are complete. If the payment method is `card_present` and isn't a digital wallet, then a [generated_card](https://docs.stripe.com/api/charges/object#charge_object-payment_method_details-card_present-generated_card) payment method representing the card is created and attached to the Customer instead. Nullable. Expandable.
  * `customer_account` - ID of the Account representing the customer that this PaymentIntent belongs to, if one exists.

  Payment methods attached to other Accounts cannot be used with this PaymentIntent.

  If [setup_future_usage](https://api.stripe.com#payment_intent_object-setup_future_usage) is set and this PaymentIntent's payment method is not `card_present`, then the payment method attaches to the Account after the PaymentIntent has been confirmed and any required actions from the user are complete. If the payment method is `card_present` and isn't a digital wallet, then a [generated_card](https://docs.stripe.com/api/charges/object#charge_object-payment_method_details-card_present-generated_card) payment method representing the card is created and attached to the Account instead. Max length: 5000. Nullable.
  * `description` - An arbitrary string attached to the object. Often useful for displaying to users. Max length: 5000. Nullable.
  * `excluded_payment_method_types` - The list of payment method types to exclude from use with this payment. Nullable.
  * `hooks` - Expandable.
  * `id` - Unique identifier for the object. Max length: 5000.
  * `last_payment_error` - The payment error encountered in the previous PaymentIntent confirmation. It will be cleared if the PaymentIntent is later updated for any reason. Nullable. Expandable.
  * `latest_charge` - ID of the latest [Charge object](https://docs.stripe.com/api/charges) created by this PaymentIntent. This property is `null` until PaymentIntent confirmation is attempted. Nullable. Expandable.
  * `livemode` - If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
  * `managed_payments` - Settings for Managed Payments. Nullable. Expandable.
  * `metadata` - Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Learn more about [storing information in metadata](https://docs.stripe.com/payments/payment-intents/creating-payment-intents#storing-information-in-metadata).
  * `next_action` - If present, this property tells you what actions you need to take in order for your customer to fulfill a payment using the provided source. Nullable. Expandable.
  * `object` - String representing the object's type. Objects of the same type share the same value. Possible values: `payment_intent`.
  * `on_behalf_of` - You can specify the settlement merchant as the
  connected account using the `on_behalf_of` attribute on the charge. See the PaymentIntents [use case for connected accounts](https://stripe.com/payments/connected-accounts) for details. Nullable. Expandable.
  * `payment_details` - Expandable.
  * `payment_method` - ID of the payment method used in this PaymentIntent. Nullable. Expandable.
  * `payment_method_configuration_details` - Information about the [payment method configuration](https://docs.stripe.com/api/payment_method_configurations) used for this PaymentIntent. Nullable. Expandable.
  * `payment_method_options` - Payment-method-specific configuration for this PaymentIntent. Nullable. Expandable.
  * `payment_method_types` - The list of payment method types (e.g. card) that this PaymentIntent is allowed to use. A comprehensive list of valid payment method types can be found [here](https://docs.stripe.com/api/payment_methods/object#payment_method_object-type).
  * `presentment_details` - Expandable.
  * `processing` - If present, this property tells you about the processing state of the payment. Nullable. Expandable.
  * `receipt_email` - Email address that the receipt for the resulting payment will be sent to. If `receipt_email` is specified for a payment in live mode, a receipt will be sent regardless of your [email settings](https://dashboard.stripe.com/account/emails). Max length: 5000. Nullable.
  * `review` - ID of the review associated with this PaymentIntent, if any. Nullable. Expandable.
  * `setup_future_usage` - Indicates that you intend to make future payments with this PaymentIntent's payment method.

  If you provide a Customer with the PaymentIntent, you can use this parameter to [attach the payment method](https://stripe.com/payments/save-during-payment) to the Customer after the PaymentIntent is confirmed and the customer completes any required actions. If you don't provide a Customer, you can still [attach](https://docs.stripe.com/api/payment_methods/attach) the payment method to a Customer after the transaction completes.

  If the payment method is `card_present` and isn't a digital wallet, Stripe creates and attaches a [generated_card](https://docs.stripe.com/api/charges/object#charge_object-payment_method_details-card_present-generated_card) payment method representing the card to the Customer instead.

  When processing card payments, Stripe uses `setup_future_usage` to help you comply with regional legislation and network rules, such as [SCA](https://stripe.com/strong-customer-authentication). Possible values: `off_session`, `on_session`. Nullable.
  * `shipping` - Shipping information for this PaymentIntent. Nullable. Expandable.
  * `source` - This is a legacy field that will be removed in the future. It is the ID of the Source object that is associated with this PaymentIntent, if one was supplied. Nullable. Expandable.
  * `statement_descriptor` - Text that appears on the customer's statement as the statement descriptor for a non-card charge. This value overrides the account's default statement descriptor. For information about requirements, including the 22-character limit, see [the Statement Descriptor docs](https://docs.stripe.com/get-started/account/statement-descriptors).

  Setting this value for a card charge returns an error. For card charges, set the [statement_descriptor_suffix](https://docs.stripe.com/get-started/account/statement-descriptors#dynamic) instead. Max length: 5000. Nullable.
  * `statement_descriptor_suffix` - Provides information about a card charge. Concatenated to the account's [statement descriptor prefix](https://docs.stripe.com/get-started/account/statement-descriptors#static) to form the complete statement descriptor that appears on the customer's statement. Max length: 5000. Nullable.
  * `status` - Status of this PaymentIntent, one of `requires_payment_method`, `requires_confirmation`, `requires_action`, `processing`, `requires_capture`, `canceled`, or `succeeded`. Read more about each PaymentIntent [status](https://docs.stripe.com/payments/intents#intent-statuses). Possible values: `canceled`, `processing`, `requires_action`, `requires_capture`, `requires_confirmation`, `requires_payment_method`, `succeeded`.
  * `transfer_data` - The data that automatically creates a Transfer after the payment finalizes. Learn more about the [use case for connected accounts](https://docs.stripe.com/payments/connected-accounts). Nullable. Expandable.
  * `transfer_group` - A string that identifies the resulting payment as part of a group. Learn more about the [use case for connected accounts](https://docs.stripe.com/connect/separate-charges-and-transfers). Max length: 5000. Nullable.
  """
  @type t :: %__MODULE__{}

  defstruct [
    :allowed_payment_method_types,
    :amount,
    :amount_capturable,
    :amount_details,
    :amount_received,
    :application,
    :application_fee_amount,
    :automatic_payment_methods,
    :canceled_at,
    :cancellation_reason,
    :capture_method,
    :client_secret,
    :confirmation_method,
    :created,
    :currency,
    :customer,
    :customer_account,
    :description,
    :excluded_payment_method_types,
    :hooks,
    :id,
    :last_payment_error,
    :latest_charge,
    :livemode,
    :managed_payments,
    :metadata,
    :next_action,
    :object,
    :on_behalf_of,
    :payment_details,
    :payment_method,
    :payment_method_configuration_details,
    :payment_method_options,
    :payment_method_types,
    :presentment_details,
    :processing,
    :receipt_email,
    :review,
    :setup_future_usage,
    :shipping,
    :source,
    :statement_descriptor,
    :statement_descriptor_suffix,
    :status,
    :transfer_data,
    :transfer_group
  ]

  @object_name "payment_intent"
  def object_name, do: @object_name

  def expandable_fields,
    do: [
      "amount_details",
      "application",
      "automatic_payment_methods",
      "customer",
      "hooks",
      "last_payment_error",
      "latest_charge",
      "managed_payments",
      "next_action",
      "on_behalf_of",
      "payment_details",
      "payment_method",
      "payment_method_configuration_details",
      "payment_method_options",
      "presentment_details",
      "processing",
      "review",
      "shipping",
      "source",
      "transfer_data"
    ]

  def __nested_fields__ do
    %{
      "amount_details" => %{
        fields: %{
          "discount_amount" => :scalar,
          "error" => %{
            fields: %{
              "code" => :scalar,
              "message" => :scalar
            }
          },
          "line_items" => %{
            fields: %{
              "data" => {:list, {:resource, Stripe.Resources.PaymentIntentAmountDetailsLineItem}},
              "has_more" => :scalar,
              "object" => :scalar,
              "url" => :scalar
            }
          },
          "shipping" => %{
            fields: %{
              "amount" => :scalar,
              "from_postal_code" => :scalar,
              "to_postal_code" => :scalar
            }
          },
          "tax" => %{
            fields: %{
              "total_tax_amount" => :scalar
            }
          },
          "tip" => %{
            fields: %{
              "amount" => :scalar
            }
          }
        }
      },
      "automatic_payment_methods" => %{
        fields: %{
          "allow_redirects" => :scalar,
          "enabled" => :scalar
        }
      },
      "hooks" => %{
        fields: %{
          "inputs" => %{
            fields: %{
              "tax" => %{
                fields: %{
                  "calculation" => :scalar
                }
              }
            }
          }
        }
      },
      "managed_payments" => %{
        fields: %{
          "enabled" => :scalar
        }
      },
      "next_action" => %{
        fields: %{
          "alipay_handle_redirect" =>
            {:resource, Stripe.Resources.NextActionAlipayHandleRedirect},
          "blik_authorize" => {:resource, Stripe.Resources.BlikAuthorize},
          "boleto_display_details" =>
            {:resource, Stripe.Resources.NextActionDisplayBoletoDetails},
          "card_await_notification" =>
            {:resource, Stripe.Resources.NextActionCardAwaitNotification},
          "cashapp_handle_redirect_or_display_qr_code" =>
            {:resource, Stripe.Resources.CashappHandleRedirectOrDisplayQrCode},
          "display_bank_transfer_instructions" =>
            {:resource, Stripe.Resources.NextActionDisplayBankTransferInstructions},
          "klarna_display_qr_code" => {:resource, Stripe.Resources.KlarnaDisplayQrCode},
          "konbini_display_details" =>
            {:resource, Stripe.Resources.NextActionKonbiniDisplayDetails},
          "multibanco_display_details" =>
            {:resource, Stripe.Resources.NextActionMultibancoDisplayDetails},
          "oxxo_display_details" => {:resource, Stripe.Resources.NextActionOxxoDisplayDetails},
          "paynow_display_qr_code" => {:resource, Stripe.Resources.PaynowDisplayQrCode},
          "pix_display_qr_code" => {:resource, Stripe.Resources.PixDisplayQrCode},
          "promptpay_display_qr_code" => {:resource, Stripe.Resources.PromptpayDisplayQrCode},
          "redirect_to_url" => {:resource, Stripe.Resources.NextActionRedirectToUrl},
          "swish_handle_redirect_or_display_qr_code" =>
            {:resource, Stripe.Resources.SwishHandleRedirectOrDisplayQrCode},
          "type" => :scalar,
          "upi_handle_redirect_or_display_qr_code" =>
            {:resource, Stripe.Resources.UPIHandleRedirectOrDisplayQrCode},
          "use_stripe_sdk" => {:map, :scalar},
          "verify_with_microdeposits" => %{
            fields: %{
              "arrival_date" => :scalar,
              "hosted_verification_url" => :scalar,
              "microdeposit_type" => :scalar
            }
          },
          "wechat_pay_display_qr_code" => {:resource, Stripe.Resources.WechatPayDisplayQrCode},
          "wechat_pay_redirect_to_android_app" =>
            {:resource, Stripe.Resources.WechatPayRedirectToAndroidApp},
          "wechat_pay_redirect_to_ios_app" =>
            {:resource, Stripe.Resources.WechatPayRedirectToIosApp}
        }
      },
      "payment_details" => %{
        fields: %{
          "customer_reference" => :scalar,
          "order_reference" => :scalar
        }
      },
      "payment_method_configuration_details" => %{
        fields: %{
          "id" => :scalar,
          "parent" => :scalar
        }
      },
      "payment_method_options" => %{
        fields: %{
          "acss_debit" => %{
            fields: %{
              "mandate_options" => %{
                fields: %{
                  "custom_mandate_url" => :scalar,
                  "interval_description" => :scalar,
                  "payment_schedule" => :scalar,
                  "transaction_type" => :scalar
                }
              },
              "setup_future_usage" => :scalar,
              "target_date" => :scalar,
              "verification_method" => :scalar
            }
          },
          "affirm" => %{
            fields: %{
              "capture_method" => :scalar,
              "preferred_locale" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "afterpay_clearpay" => %{
            fields: %{
              "capture_method" => :scalar,
              "reference" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "alipay" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "alma" => %{
            fields: %{
              "capture_method" => :scalar
            }
          },
          "amazon_pay" => %{
            fields: %{
              "capture_method" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "au_becs_debit" => %{
            fields: %{
              "setup_future_usage" => :scalar,
              "target_date" => :scalar
            }
          },
          "bacs_debit" => %{
            fields: %{
              "mandate_options" => {:resource, Stripe.Resources.BacsDebitMandateOptions},
              "setup_future_usage" => :scalar,
              "target_date" => :scalar
            }
          },
          "bancontact" => %{
            fields: %{
              "preferred_language" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "billie" => %{
            fields: %{
              "capture_method" => :scalar
            }
          },
          "bizum" => :scalar,
          "blik" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "boleto" => %{
            fields: %{
              "expires_after_days" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "card" => %{
            fields: %{
              "capture_method" => :scalar,
              "installments" => %{
                fields: %{
                  "available_plans" =>
                    {:list,
                     %{
                       fields: %{
                         "count" => :scalar,
                         "interval" => :scalar,
                         "type" => :scalar
                       }
                     }},
                  "enabled" => :scalar,
                  "plan" => %{
                    fields: %{
                      "count" => :scalar,
                      "interval" => :scalar,
                      "type" => :scalar
                    }
                  }
                }
              },
              "mandate_options" => {:resource, Stripe.Resources.MandateOptions},
              "network" => :scalar,
              "request_extended_authorization" => :scalar,
              "request_incremental_authorization" => :scalar,
              "request_multicapture" => :scalar,
              "request_overcapture" => :scalar,
              "request_three_d_secure" => :scalar,
              "require_cvc_recollection" => :scalar,
              "setup_future_usage" => :scalar,
              "statement_descriptor_suffix_kana" => :scalar,
              "statement_descriptor_suffix_kanji" => :scalar
            }
          },
          "card_present" => %{
            fields: %{
              "capture_method" => :scalar,
              "request_extended_authorization" => :scalar,
              "request_incremental_authorization_support" => :scalar,
              "routing" => {:resource, Stripe.Resources.Routing}
            }
          },
          "cashapp" => %{
            fields: %{
              "capture_method" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "crypto" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "customer_balance" => %{
            fields: %{
              "bank_transfer" => %{
                fields: %{
                  "eu_bank_transfer" => %{
                    fields: %{
                      "country" => :scalar
                    }
                  },
                  "requested_address_types" => {:list, :scalar},
                  "type" => :scalar
                }
              },
              "funding_type" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "eps" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "fpx" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "giropay" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "grabpay" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "ideal" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "interac_present" => :scalar,
          "kakao_pay" => %{
            fields: %{
              "capture_method" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "klarna" => %{
            fields: %{
              "capture_method" => :scalar,
              "preferred_locale" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "konbini" => %{
            fields: %{
              "confirmation_number" => :scalar,
              "expires_after_days" => :scalar,
              "expires_at" => :scalar,
              "product_description" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "kr_card" => %{
            fields: %{
              "capture_method" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "link" => %{
            fields: %{
              "capture_method" => :scalar,
              "persistent_token" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "mb_way" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "mobilepay" => %{
            fields: %{
              "capture_method" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "multibanco" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "naver_pay" => %{
            fields: %{
              "capture_method" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "nz_bank_account" => %{
            fields: %{
              "setup_future_usage" => :scalar,
              "target_date" => :scalar
            }
          },
          "oxxo" => %{
            fields: %{
              "expires_after_days" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "p24" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "pay_by_bank" => :scalar,
          "payco" => %{
            fields: %{
              "capture_method" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "paynow" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "paypal" => %{
            fields: %{
              "capture_method" => :scalar,
              "preferred_locale" => :scalar,
              "reference" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "payto" => %{
            fields: %{
              "mandate_options" => %{
                fields: %{
                  "amount" => :scalar,
                  "amount_type" => :scalar,
                  "end_date" => :scalar,
                  "payment_schedule" => :scalar,
                  "payments_per_period" => :scalar,
                  "purpose" => :scalar
                }
              },
              "setup_future_usage" => :scalar
            }
          },
          "pix" => %{
            fields: %{
              "amount_includes_iof" => :scalar,
              "expires_after_seconds" => :scalar,
              "expires_at" => :scalar,
              "mandate_options" => %{
                fields: %{
                  "amount" => :scalar,
                  "amount_includes_iof" => :scalar,
                  "amount_type" => :scalar,
                  "currency" => :scalar,
                  "end_date" => :scalar,
                  "payment_schedule" => :scalar,
                  "reference" => :scalar,
                  "start_date" => :scalar
                }
              },
              "setup_future_usage" => :scalar
            }
          },
          "promptpay" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "revolut_pay" => %{
            fields: %{
              "capture_method" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "samsung_pay" => %{
            fields: %{
              "capture_method" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "satispay" => %{
            fields: %{
              "capture_method" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "scalapay" => %{
            fields: %{
              "capture_method" => :scalar
            }
          },
          "sepa_debit" => %{
            fields: %{
              "mandate_options" => {:resource, Stripe.Resources.SepaDebitMandateOptions},
              "setup_future_usage" => :scalar,
              "target_date" => :scalar
            }
          },
          "sofort" => %{
            fields: %{
              "preferred_language" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "sunbit" => %{
            fields: %{
              "capture_method" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "swish" => %{
            fields: %{
              "reference" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "twint" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "upi" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          },
          "us_bank_account" => %{
            fields: %{
              "financial_connections" => %{
                fields: %{
                  "filters" => %{
                    fields: %{
                      "account_subcategories" => {:list, :scalar}
                    }
                  },
                  "permissions" => {:list, :scalar},
                  "prefetch" => {:list, :scalar},
                  "return_url" => :scalar
                }
              },
              "mandate_options" => %{
                fields: %{
                  "collection_method" => :scalar
                }
              },
              "setup_future_usage" => :scalar,
              "target_date" => :scalar,
              "transaction_purpose" => :scalar,
              "verification_method" => :scalar
            }
          },
          "wechat_pay" => %{
            fields: %{
              "app_id" => :scalar,
              "client" => :scalar,
              "setup_future_usage" => :scalar
            }
          },
          "zip" => %{
            fields: %{
              "setup_future_usage" => :scalar
            }
          }
        }
      },
      "presentment_details" => %{
        fields: %{
          "presentment_amount" => :scalar,
          "presentment_currency" => :scalar
        }
      },
      "processing" => %{
        fields: %{
          "card" => {:resource, Stripe.Resources.Card},
          "type" => :scalar
        }
      },
      "transfer_data" => %{
        fields: %{
          "amount" => :scalar,
          "description" => :scalar,
          "destination" => {:resource, Stripe.Resources.Account},
          "metadata" => {:map, :scalar},
          "payment_data" => %{
            fields: %{
              "description" => :scalar,
              "metadata" => {:map, :scalar}
            }
          }
        }
      },
      "last_payment_error" => {:resource, Stripe.Resources.StripeError},
      "shipping" => {:resource, Stripe.Resources.ShippingDetails}
    }
  end
end
