# File generated from our OpenAPI spec
defmodule Stripe.Resources.V2.Core.Event do
  @moduledoc """
  Event

  Events are generated to keep you informed of activity in your business account. APIs in the /v2 namespace generate [thin events](https://docs.stripe.com/event-destinations#benefits-of-thin-events) which have small, unversioned payloads that include a reference to the ID of the object that has changed. The Events v2 API returns these new thin events. [Retrieve the event object](https://docs.stripe.com/event-destinations#fetch-data) for additional data about the event. Use the related object ID in the event payload to [fetch the API resource](https://docs.stripe.com/event-destinations#retrieve-the-object-associated-with-thin-events) of the object associated with the event. Comparatively, events generated by most API v1 include a versioned snapshot of an API object in their payload.
  """

  @typedoc """
  * `changes` - Before and after changes for the primary related object.
  * `context` - Authentication context needed to fetch the event or related object.
  * `created` - Time at which the object was created. Format: date-time.
  * `id` - Unique identifier for the event.
  * `livemode` - Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
  * `object` - String representing the object's type. Objects of the same type share the same value of the object field. Possible values: `v2.core.event`.
  * `reason` - Reason for the event.
  * `type` - The type of the event.
  """
  @type t :: %__MODULE__{}

  defstruct [:changes, :context, :created, :id, :livemode, :object, :reason, :type]

  @object_name "v2.core.event"
  def object_name, do: @object_name

  def __nested_fields__ do
    %{
      "reason" => %{
        fields: %{
          "request" => %{
            fields: %{
              "id" => :scalar,
              "idempotency_key" => :scalar
            }
          },
          "type" => :scalar
        }
      }
    }
  end
end
